server:
  port: 8091
  servlet:
    context-path: /eurekaClienter
spring:
  application:
    name: eureka-clienter
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-cluster7001.com:7001/eureka/,http://eureka-cluster7002.com:7002/eureka/,http://eureka-cluster7003.com:7003//eureka/
  instance:
    prefer-ip-address: true
#feign的配置，连接超时及读取超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 1000
        loggerLevel: basic
