spring:
  application:
    name: demo-dubbo-comsumer
  cloud:
    nacos:
      discovery:
        server-addr: tt.hori-gz.com:8848
        username: nacos
        password: nacos
server:
  servlet:
    context-path: /demo-dubbo-comsumer
  port: 8081
#dubbo配置
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://tt.hori-gz.com
    subscribe: true
    register: false #项目只使用dubbo服务，不注册服务
  cloud:
    subscribed-services: demo-dubbo-service
  consumer:
    version: 1.1 #消费服务的版本号
  application:
    name: demo-dubbo-comsumer1