package com.gzzsc.lai.provider.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AdvertisementExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    public AdvertisementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNull() {
            addCriterion("customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNotNull() {
            addCriterion("customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdEqualTo(String value) {
            addCriterion("customer_id =", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotEqualTo(String value) {
            addCriterion("customer_id <>", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThan(String value) {
            addCriterion("customer_id >", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThanOrEqualTo(String value) {
            addCriterion("customer_id >=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThan(String value) {
            addCriterion("customer_id <", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThanOrEqualTo(String value) {
            addCriterion("customer_id <=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLike(String value) {
            addCriterion("customer_id like", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotLike(String value) {
            addCriterion("customer_id not like", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIn(List<String> values) {
            addCriterion("customer_id in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotIn(List<String> values) {
            addCriterion("customer_id not in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdBetween(String value1, String value2) {
            addCriterion("customer_id between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotBetween(String value1, String value2) {
            addCriterion("customer_id not between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNull() {
            addCriterion("contract_id is null");
            return (Criteria) this;
        }

        public Criteria andContractIdIsNotNull() {
            addCriterion("contract_id is not null");
            return (Criteria) this;
        }

        public Criteria andContractIdEqualTo(String value) {
            addCriterion("contract_id =", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotEqualTo(String value) {
            addCriterion("contract_id <>", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThan(String value) {
            addCriterion("contract_id >", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdGreaterThanOrEqualTo(String value) {
            addCriterion("contract_id >=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThan(String value) {
            addCriterion("contract_id <", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLessThanOrEqualTo(String value) {
            addCriterion("contract_id <=", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdLike(String value) {
            addCriterion("contract_id like", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotLike(String value) {
            addCriterion("contract_id not like", value, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdIn(List<String> values) {
            addCriterion("contract_id in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotIn(List<String> values) {
            addCriterion("contract_id not in", values, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdBetween(String value1, String value2) {
            addCriterion("contract_id between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andContractIdNotBetween(String value1, String value2) {
            addCriterion("contract_id not between", value1, value2, "contractId");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNull() {
            addCriterion("begin_time is null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIsNotNull() {
            addCriterion("begin_time is not null");
            return (Criteria) this;
        }

        public Criteria andBeginTimeEqualTo(Date value) {
            addCriterion("begin_time =", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotEqualTo(Date value) {
            addCriterion("begin_time <>", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThan(Date value) {
            addCriterion("begin_time >", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("begin_time >=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThan(Date value) {
            addCriterion("begin_time <", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeLessThanOrEqualTo(Date value) {
            addCriterion("begin_time <=", value, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeIn(List<Date> values) {
            addCriterion("begin_time in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotIn(List<Date> values) {
            addCriterion("begin_time not in", values, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeBetween(Date value1, Date value2) {
            addCriterion("begin_time between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andBeginTimeNotBetween(Date value1, Date value2) {
            addCriterion("begin_time not between", value1, value2, "beginTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNull() {
            addCriterion("account_id is null");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNotNull() {
            addCriterion("account_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccountIdEqualTo(String value) {
            addCriterion("account_id =", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotEqualTo(String value) {
            addCriterion("account_id <>", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThan(String value) {
            addCriterion("account_id >", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThanOrEqualTo(String value) {
            addCriterion("account_id >=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThan(String value) {
            addCriterion("account_id <", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThanOrEqualTo(String value) {
            addCriterion("account_id <=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLike(String value) {
            addCriterion("account_id like", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotLike(String value) {
            addCriterion("account_id not like", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdIn(List<String> values) {
            addCriterion("account_id in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotIn(List<String> values) {
            addCriterion("account_id not in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdBetween(String value1, String value2) {
            addCriterion("account_id between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotBetween(String value1, String value2) {
            addCriterion("account_id not between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andRoleLevelIsNull() {
            addCriterion("role_level is null");
            return (Criteria) this;
        }

        public Criteria andRoleLevelIsNotNull() {
            addCriterion("role_level is not null");
            return (Criteria) this;
        }

        public Criteria andRoleLevelEqualTo(String value) {
            addCriterion("role_level =", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelNotEqualTo(String value) {
            addCriterion("role_level <>", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelGreaterThan(String value) {
            addCriterion("role_level >", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelGreaterThanOrEqualTo(String value) {
            addCriterion("role_level >=", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelLessThan(String value) {
            addCriterion("role_level <", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelLessThanOrEqualTo(String value) {
            addCriterion("role_level <=", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelLike(String value) {
            addCriterion("role_level like", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelNotLike(String value) {
            addCriterion("role_level not like", value, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelIn(List<String> values) {
            addCriterion("role_level in", values, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelNotIn(List<String> values) {
            addCriterion("role_level not in", values, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelBetween(String value1, String value2) {
            addCriterion("role_level between", value1, value2, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andRoleLevelNotBetween(String value1, String value2) {
            addCriterion("role_level not between", value1, value2, "roleLevel");
            return (Criteria) this;
        }

        public Criteria andAttchmentIdIsNull() {
            addCriterion("attchment_id is null");
            return (Criteria) this;
        }

        public Criteria andAttchmentIdIsNotNull() {
            addCriterion("attchment_id is not null");
            return (Criteria) this;
        }

        public Criteria andAttchmentIdEqualTo(String value) {
            addCriterion("attchment_id =", value, "attchmentId");
            return (Criteria) this;
        }

        public Criteria andAttchmentIdNotEqualTo(String value) {
            addCriterion("attchment_id <>", value, "attchmentId");
            return (Criteria) this;
        }

        public Criteria andAttchmentIdGreaterThan(String value) {
            addCriterion("attchment_id >", value, "attchmentId");
            return (Criteria) this;
        }

        public Criteria andAttchmentIdGreaterThanOrEqualTo(String value) {
            addCriterion("attchment_id >=", value, "attchmentId");
            return (Criteria) this;
        }

        public Criteria andAttchmentIdLessThan(String value) {
            addCriterion("attchment_id <", value, "attchmentId");
            return (Criteria) this;
        }

        public Criteria andAttchmentIdLessThanOrEqualTo(String value) {
            addCriterion("attchment_id <=", value, "attchmentId");
            return (Criteria) this;
        }

        public Criteria andAttchmentIdLike(String value) {
            addCriterion("attchment_id like", value, "attchmentId");
            return (Criteria) this;
        }

        public Criteria andAttchmentIdNotLike(String value) {
            addCriterion("attchment_id not like", value, "attchmentId");
            return (Criteria) this;
        }

        public Criteria andAttchmentIdIn(List<String> values) {
            addCriterion("attchment_id in", values, "attchmentId");
            return (Criteria) this;
        }

        public Criteria andAttchmentIdNotIn(List<String> values) {
            addCriterion("attchment_id not in", values, "attchmentId");
            return (Criteria) this;
        }

        public Criteria andAttchmentIdBetween(String value1, String value2) {
            addCriterion("attchment_id between", value1, value2, "attchmentId");
            return (Criteria) this;
        }

        public Criteria andAttchmentIdNotBetween(String value1, String value2) {
            addCriterion("attchment_id not between", value1, value2, "attchmentId");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Short value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Short value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Short value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Short value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Short value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Short value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Short> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Short> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Short value1, Short value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Short value1, Short value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCommentIsNull() {
            addCriterion("comment is null");
            return (Criteria) this;
        }

        public Criteria andCommentIsNotNull() {
            addCriterion("comment is not null");
            return (Criteria) this;
        }

        public Criteria andCommentEqualTo(String value) {
            addCriterion("comment =", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotEqualTo(String value) {
            addCriterion("comment <>", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThan(String value) {
            addCriterion("comment >", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentGreaterThanOrEqualTo(String value) {
            addCriterion("comment >=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThan(String value) {
            addCriterion("comment <", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLessThanOrEqualTo(String value) {
            addCriterion("comment <=", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentLike(String value) {
            addCriterion("comment like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotLike(String value) {
            addCriterion("comment not like", value, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentIn(List<String> values) {
            addCriterion("comment in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotIn(List<String> values) {
            addCriterion("comment not in", values, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentBetween(String value1, String value2) {
            addCriterion("comment between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andCommentNotBetween(String value1, String value2) {
            addCriterion("comment not between", value1, value2, "comment");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Byte value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Byte value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Byte value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Byte value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Byte value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Byte> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Byte> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Byte value1, Byte value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNull() {
            addCriterion("modified_time is null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIsNotNull() {
            addCriterion("modified_time is not null");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeEqualTo(Date value) {
            addCriterion("modified_time =", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotEqualTo(Date value) {
            addCriterion("modified_time <>", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThan(Date value) {
            addCriterion("modified_time >", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("modified_time >=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThan(Date value) {
            addCriterion("modified_time <", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeLessThanOrEqualTo(Date value) {
            addCriterion("modified_time <=", value, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeIn(List<Date> values) {
            addCriterion("modified_time in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotIn(List<Date> values) {
            addCriterion("modified_time not in", values, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeBetween(Date value1, Date value2) {
            addCriterion("modified_time between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andModifiedTimeNotBetween(Date value1, Date value2) {
            addCriterion("modified_time not between", value1, value2, "modifiedTime");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Byte value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Byte value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Byte value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Byte value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Byte value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Byte> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Byte> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Byte value1, Byte value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andEnableIsNull() {
            addCriterion("enable is null");
            return (Criteria) this;
        }

        public Criteria andEnableIsNotNull() {
            addCriterion("enable is not null");
            return (Criteria) this;
        }

        public Criteria andEnableEqualTo(Byte value) {
            addCriterion("enable =", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotEqualTo(Byte value) {
            addCriterion("enable <>", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThan(Byte value) {
            addCriterion("enable >", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableGreaterThanOrEqualTo(Byte value) {
            addCriterion("enable >=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThan(Byte value) {
            addCriterion("enable <", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableLessThanOrEqualTo(Byte value) {
            addCriterion("enable <=", value, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableIn(List<Byte> values) {
            addCriterion("enable in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotIn(List<Byte> values) {
            addCriterion("enable not in", values, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableBetween(Byte value1, Byte value2) {
            addCriterion("enable between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andEnableNotBetween(Byte value1, Byte value2) {
            addCriterion("enable not between", value1, value2, "enable");
            return (Criteria) this;
        }

        public Criteria andAeStatusIsNull() {
            addCriterion("ae_status is null");
            return (Criteria) this;
        }

        public Criteria andAeStatusIsNotNull() {
            addCriterion("ae_status is not null");
            return (Criteria) this;
        }

        public Criteria andAeStatusEqualTo(Byte value) {
            addCriterion("ae_status =", value, "aeStatus");
            return (Criteria) this;
        }

        public Criteria andAeStatusNotEqualTo(Byte value) {
            addCriterion("ae_status <>", value, "aeStatus");
            return (Criteria) this;
        }

        public Criteria andAeStatusGreaterThan(Byte value) {
            addCriterion("ae_status >", value, "aeStatus");
            return (Criteria) this;
        }

        public Criteria andAeStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("ae_status >=", value, "aeStatus");
            return (Criteria) this;
        }

        public Criteria andAeStatusLessThan(Byte value) {
            addCriterion("ae_status <", value, "aeStatus");
            return (Criteria) this;
        }

        public Criteria andAeStatusLessThanOrEqualTo(Byte value) {
            addCriterion("ae_status <=", value, "aeStatus");
            return (Criteria) this;
        }

        public Criteria andAeStatusIn(List<Byte> values) {
            addCriterion("ae_status in", values, "aeStatus");
            return (Criteria) this;
        }

        public Criteria andAeStatusNotIn(List<Byte> values) {
            addCriterion("ae_status not in", values, "aeStatus");
            return (Criteria) this;
        }

        public Criteria andAeStatusBetween(Byte value1, Byte value2) {
            addCriterion("ae_status between", value1, value2, "aeStatus");
            return (Criteria) this;
        }

        public Criteria andAeStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("ae_status not between", value1, value2, "aeStatus");
            return (Criteria) this;
        }

        public Criteria andClassifyIsNull() {
            addCriterion("classify is null");
            return (Criteria) this;
        }

        public Criteria andClassifyIsNotNull() {
            addCriterion("classify is not null");
            return (Criteria) this;
        }

        public Criteria andClassifyEqualTo(Integer value) {
            addCriterion("classify =", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyNotEqualTo(Integer value) {
            addCriterion("classify <>", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyGreaterThan(Integer value) {
            addCriterion("classify >", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyGreaterThanOrEqualTo(Integer value) {
            addCriterion("classify >=", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyLessThan(Integer value) {
            addCriterion("classify <", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyLessThanOrEqualTo(Integer value) {
            addCriterion("classify <=", value, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyIn(List<Integer> values) {
            addCriterion("classify in", values, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyNotIn(List<Integer> values) {
            addCriterion("classify not in", values, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyBetween(Integer value1, Integer value2) {
            addCriterion("classify between", value1, value2, "classify");
            return (Criteria) this;
        }

        public Criteria andClassifyNotBetween(Integer value1, Integer value2) {
            addCriterion("classify not between", value1, value2, "classify");
            return (Criteria) this;
        }

        public Criteria andUserSawTimesIsNull() {
            addCriterion("user_saw_times is null");
            return (Criteria) this;
        }

        public Criteria andUserSawTimesIsNotNull() {
            addCriterion("user_saw_times is not null");
            return (Criteria) this;
        }

        public Criteria andUserSawTimesEqualTo(String value) {
            addCriterion("user_saw_times =", value, "userSawTimes");
            return (Criteria) this;
        }

        public Criteria andUserSawTimesNotEqualTo(String value) {
            addCriterion("user_saw_times <>", value, "userSawTimes");
            return (Criteria) this;
        }

        public Criteria andUserSawTimesGreaterThan(String value) {
            addCriterion("user_saw_times >", value, "userSawTimes");
            return (Criteria) this;
        }

        public Criteria andUserSawTimesGreaterThanOrEqualTo(String value) {
            addCriterion("user_saw_times >=", value, "userSawTimes");
            return (Criteria) this;
        }

        public Criteria andUserSawTimesLessThan(String value) {
            addCriterion("user_saw_times <", value, "userSawTimes");
            return (Criteria) this;
        }

        public Criteria andUserSawTimesLessThanOrEqualTo(String value) {
            addCriterion("user_saw_times <=", value, "userSawTimes");
            return (Criteria) this;
        }

        public Criteria andUserSawTimesLike(String value) {
            addCriterion("user_saw_times like", value, "userSawTimes");
            return (Criteria) this;
        }

        public Criteria andUserSawTimesNotLike(String value) {
            addCriterion("user_saw_times not like", value, "userSawTimes");
            return (Criteria) this;
        }

        public Criteria andUserSawTimesIn(List<String> values) {
            addCriterion("user_saw_times in", values, "userSawTimes");
            return (Criteria) this;
        }

        public Criteria andUserSawTimesNotIn(List<String> values) {
            addCriterion("user_saw_times not in", values, "userSawTimes");
            return (Criteria) this;
        }

        public Criteria andUserSawTimesBetween(String value1, String value2) {
            addCriterion("user_saw_times between", value1, value2, "userSawTimes");
            return (Criteria) this;
        }

        public Criteria andUserSawTimesNotBetween(String value1, String value2) {
            addCriterion("user_saw_times not between", value1, value2, "userSawTimes");
            return (Criteria) this;
        }

        public Criteria andPlayTimesIsNull() {
            addCriterion("play_times is null");
            return (Criteria) this;
        }

        public Criteria andPlayTimesIsNotNull() {
            addCriterion("play_times is not null");
            return (Criteria) this;
        }

        public Criteria andPlayTimesEqualTo(String value) {
            addCriterion("play_times =", value, "playTimes");
            return (Criteria) this;
        }

        public Criteria andPlayTimesNotEqualTo(String value) {
            addCriterion("play_times <>", value, "playTimes");
            return (Criteria) this;
        }

        public Criteria andPlayTimesGreaterThan(String value) {
            addCriterion("play_times >", value, "playTimes");
            return (Criteria) this;
        }

        public Criteria andPlayTimesGreaterThanOrEqualTo(String value) {
            addCriterion("play_times >=", value, "playTimes");
            return (Criteria) this;
        }

        public Criteria andPlayTimesLessThan(String value) {
            addCriterion("play_times <", value, "playTimes");
            return (Criteria) this;
        }

        public Criteria andPlayTimesLessThanOrEqualTo(String value) {
            addCriterion("play_times <=", value, "playTimes");
            return (Criteria) this;
        }

        public Criteria andPlayTimesLike(String value) {
            addCriterion("play_times like", value, "playTimes");
            return (Criteria) this;
        }

        public Criteria andPlayTimesNotLike(String value) {
            addCriterion("play_times not like", value, "playTimes");
            return (Criteria) this;
        }

        public Criteria andPlayTimesIn(List<String> values) {
            addCriterion("play_times in", values, "playTimes");
            return (Criteria) this;
        }

        public Criteria andPlayTimesNotIn(List<String> values) {
            addCriterion("play_times not in", values, "playTimes");
            return (Criteria) this;
        }

        public Criteria andPlayTimesBetween(String value1, String value2) {
            addCriterion("play_times between", value1, value2, "playTimes");
            return (Criteria) this;
        }

        public Criteria andPlayTimesNotBetween(String value1, String value2) {
            addCriterion("play_times not between", value1, value2, "playTimes");
            return (Criteria) this;
        }

        public Criteria andScheduleBegintimeIsNull() {
            addCriterion("schedule_beginTime is null");
            return (Criteria) this;
        }

        public Criteria andScheduleBegintimeIsNotNull() {
            addCriterion("schedule_beginTime is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleBegintimeEqualTo(Date value) {
            addCriterion("schedule_beginTime =", value, "scheduleBegintime");
            return (Criteria) this;
        }

        public Criteria andScheduleBegintimeNotEqualTo(Date value) {
            addCriterion("schedule_beginTime <>", value, "scheduleBegintime");
            return (Criteria) this;
        }

        public Criteria andScheduleBegintimeGreaterThan(Date value) {
            addCriterion("schedule_beginTime >", value, "scheduleBegintime");
            return (Criteria) this;
        }

        public Criteria andScheduleBegintimeGreaterThanOrEqualTo(Date value) {
            addCriterion("schedule_beginTime >=", value, "scheduleBegintime");
            return (Criteria) this;
        }

        public Criteria andScheduleBegintimeLessThan(Date value) {
            addCriterion("schedule_beginTime <", value, "scheduleBegintime");
            return (Criteria) this;
        }

        public Criteria andScheduleBegintimeLessThanOrEqualTo(Date value) {
            addCriterion("schedule_beginTime <=", value, "scheduleBegintime");
            return (Criteria) this;
        }

        public Criteria andScheduleBegintimeIn(List<Date> values) {
            addCriterion("schedule_beginTime in", values, "scheduleBegintime");
            return (Criteria) this;
        }

        public Criteria andScheduleBegintimeNotIn(List<Date> values) {
            addCriterion("schedule_beginTime not in", values, "scheduleBegintime");
            return (Criteria) this;
        }

        public Criteria andScheduleBegintimeBetween(Date value1, Date value2) {
            addCriterion("schedule_beginTime between", value1, value2, "scheduleBegintime");
            return (Criteria) this;
        }

        public Criteria andScheduleBegintimeNotBetween(Date value1, Date value2) {
            addCriterion("schedule_beginTime not between", value1, value2, "scheduleBegintime");
            return (Criteria) this;
        }

        public Criteria andScheduleEndtimeIsNull() {
            addCriterion("schedule_endTime is null");
            return (Criteria) this;
        }

        public Criteria andScheduleEndtimeIsNotNull() {
            addCriterion("schedule_endTime is not null");
            return (Criteria) this;
        }

        public Criteria andScheduleEndtimeEqualTo(Date value) {
            addCriterion("schedule_endTime =", value, "scheduleEndtime");
            return (Criteria) this;
        }

        public Criteria andScheduleEndtimeNotEqualTo(Date value) {
            addCriterion("schedule_endTime <>", value, "scheduleEndtime");
            return (Criteria) this;
        }

        public Criteria andScheduleEndtimeGreaterThan(Date value) {
            addCriterion("schedule_endTime >", value, "scheduleEndtime");
            return (Criteria) this;
        }

        public Criteria andScheduleEndtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("schedule_endTime >=", value, "scheduleEndtime");
            return (Criteria) this;
        }

        public Criteria andScheduleEndtimeLessThan(Date value) {
            addCriterion("schedule_endTime <", value, "scheduleEndtime");
            return (Criteria) this;
        }

        public Criteria andScheduleEndtimeLessThanOrEqualTo(Date value) {
            addCriterion("schedule_endTime <=", value, "scheduleEndtime");
            return (Criteria) this;
        }

        public Criteria andScheduleEndtimeIn(List<Date> values) {
            addCriterion("schedule_endTime in", values, "scheduleEndtime");
            return (Criteria) this;
        }

        public Criteria andScheduleEndtimeNotIn(List<Date> values) {
            addCriterion("schedule_endTime not in", values, "scheduleEndtime");
            return (Criteria) this;
        }

        public Criteria andScheduleEndtimeBetween(Date value1, Date value2) {
            addCriterion("schedule_endTime between", value1, value2, "scheduleEndtime");
            return (Criteria) this;
        }

        public Criteria andScheduleEndtimeNotBetween(Date value1, Date value2) {
            addCriterion("schedule_endTime not between", value1, value2, "scheduleEndtime");
            return (Criteria) this;
        }

        public Criteria andOpenTimesIsNull() {
            addCriterion("open_times is null");
            return (Criteria) this;
        }

        public Criteria andOpenTimesIsNotNull() {
            addCriterion("open_times is not null");
            return (Criteria) this;
        }

        public Criteria andOpenTimesEqualTo(Long value) {
            addCriterion("open_times =", value, "openTimes");
            return (Criteria) this;
        }

        public Criteria andOpenTimesNotEqualTo(Long value) {
            addCriterion("open_times <>", value, "openTimes");
            return (Criteria) this;
        }

        public Criteria andOpenTimesGreaterThan(Long value) {
            addCriterion("open_times >", value, "openTimes");
            return (Criteria) this;
        }

        public Criteria andOpenTimesGreaterThanOrEqualTo(Long value) {
            addCriterion("open_times >=", value, "openTimes");
            return (Criteria) this;
        }

        public Criteria andOpenTimesLessThan(Long value) {
            addCriterion("open_times <", value, "openTimes");
            return (Criteria) this;
        }

        public Criteria andOpenTimesLessThanOrEqualTo(Long value) {
            addCriterion("open_times <=", value, "openTimes");
            return (Criteria) this;
        }

        public Criteria andOpenTimesIn(List<Long> values) {
            addCriterion("open_times in", values, "openTimes");
            return (Criteria) this;
        }

        public Criteria andOpenTimesNotIn(List<Long> values) {
            addCriterion("open_times not in", values, "openTimes");
            return (Criteria) this;
        }

        public Criteria andOpenTimesBetween(Long value1, Long value2) {
            addCriterion("open_times between", value1, value2, "openTimes");
            return (Criteria) this;
        }

        public Criteria andOpenTimesNotBetween(Long value1, Long value2) {
            addCriterion("open_times not between", value1, value2, "openTimes");
            return (Criteria) this;
        }

        public Criteria andJumpTimesIsNull() {
            addCriterion("jump_times is null");
            return (Criteria) this;
        }

        public Criteria andJumpTimesIsNotNull() {
            addCriterion("jump_times is not null");
            return (Criteria) this;
        }

        public Criteria andJumpTimesEqualTo(Long value) {
            addCriterion("jump_times =", value, "jumpTimes");
            return (Criteria) this;
        }

        public Criteria andJumpTimesNotEqualTo(Long value) {
            addCriterion("jump_times <>", value, "jumpTimes");
            return (Criteria) this;
        }

        public Criteria andJumpTimesGreaterThan(Long value) {
            addCriterion("jump_times >", value, "jumpTimes");
            return (Criteria) this;
        }

        public Criteria andJumpTimesGreaterThanOrEqualTo(Long value) {
            addCriterion("jump_times >=", value, "jumpTimes");
            return (Criteria) this;
        }

        public Criteria andJumpTimesLessThan(Long value) {
            addCriterion("jump_times <", value, "jumpTimes");
            return (Criteria) this;
        }

        public Criteria andJumpTimesLessThanOrEqualTo(Long value) {
            addCriterion("jump_times <=", value, "jumpTimes");
            return (Criteria) this;
        }

        public Criteria andJumpTimesIn(List<Long> values) {
            addCriterion("jump_times in", values, "jumpTimes");
            return (Criteria) this;
        }

        public Criteria andJumpTimesNotIn(List<Long> values) {
            addCriterion("jump_times not in", values, "jumpTimes");
            return (Criteria) this;
        }

        public Criteria andJumpTimesBetween(Long value1, Long value2) {
            addCriterion("jump_times between", value1, value2, "jumpTimes");
            return (Criteria) this;
        }

        public Criteria andJumpTimesNotBetween(Long value1, Long value2) {
            addCriterion("jump_times not between", value1, value2, "jumpTimes");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table advertisement
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table advertisement
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}