server:
  port: 8080
  servlet:
    context-path: /eurekaServer
spring:
  application:
    name: eurekaServer
eureka:
  instance:
    #服务注册中心主机名
    hostname: localhost
    appname: 注册中心
  client:
    #是否向服务注册中心注册自己
    register-with-eureka: false
    #是否检索服务
    fetch-registry: false