server:
  servlet:
    context-path: /demo-es
  port: 80
##数据库 datasource配置
spring:
  datasource:
    url: jdbc:mysql://rm-m5e84pk3iwfq88916no.mysql.rds.aliyuncs.com:3306/adms?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: wsrp
    password: TT_mysql123
    type: com.alibaba.druid.pool.DruidDataSource #数据库连接池
  data:
    elasticsearch:
      cluster-name: singleton
      cluster-nodes: 192.168.126.3:9300
  elasticsearch:
    rest:
      uris: http://192.168.126.3:9200
initial-import:
  enabled: false
#mybatis配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
#mybatis日志
logging:
  level:
    com:
      gzzsc:
        lai:
          mapper: debug

