spring:
  application:
    name: demo-dubbo-service
  cloud:
    nacos:
      discovery:
        server-addr: tt.hori-gz.com:8848
        username: nacos
        password: nacos
server:
  servlet:
    context-path: /demo-dubbo-service
  port: 8080
##dubbo配置
dubbo:
  scan:
    base-packages: com.gzzsc.lai.dubbo.impl
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: spring-cloud://tt.hori-gz.com
  provider:
    retries: 0    #消费方调用服务超时或失败时，重试次数为0
    timeout: 10000 #服务方法超时时间
    version: 1.1  #服务版本号
    threads: 500 #处理线程数

