package com.gzzsc.lai.provider.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CommunityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table community
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table community
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table community
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated
     */
    public CommunityExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table community
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table community
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andSerialIsNull() {
            addCriterion("serial is null");
            return (Criteria) this;
        }

        public Criteria andSerialIsNotNull() {
            addCriterion("serial is not null");
            return (Criteria) this;
        }

        public Criteria andSerialEqualTo(String value) {
            addCriterion("serial =", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotEqualTo(String value) {
            addCriterion("serial <>", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialGreaterThan(String value) {
            addCriterion("serial >", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialGreaterThanOrEqualTo(String value) {
            addCriterion("serial >=", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialLessThan(String value) {
            addCriterion("serial <", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialLessThanOrEqualTo(String value) {
            addCriterion("serial <=", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialLike(String value) {
            addCriterion("serial like", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotLike(String value) {
            addCriterion("serial not like", value, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialIn(List<String> values) {
            addCriterion("serial in", values, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotIn(List<String> values) {
            addCriterion("serial not in", values, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialBetween(String value1, String value2) {
            addCriterion("serial between", value1, value2, "serial");
            return (Criteria) this;
        }

        public Criteria andSerialNotBetween(String value1, String value2) {
            addCriterion("serial not between", value1, value2, "serial");
            return (Criteria) this;
        }

        public Criteria andOrganizationSeqIsNull() {
            addCriterion("organization_seq is null");
            return (Criteria) this;
        }

        public Criteria andOrganizationSeqIsNotNull() {
            addCriterion("organization_seq is not null");
            return (Criteria) this;
        }

        public Criteria andOrganizationSeqEqualTo(String value) {
            addCriterion("organization_seq =", value, "organizationSeq");
            return (Criteria) this;
        }

        public Criteria andOrganizationSeqNotEqualTo(String value) {
            addCriterion("organization_seq <>", value, "organizationSeq");
            return (Criteria) this;
        }

        public Criteria andOrganizationSeqGreaterThan(String value) {
            addCriterion("organization_seq >", value, "organizationSeq");
            return (Criteria) this;
        }

        public Criteria andOrganizationSeqGreaterThanOrEqualTo(String value) {
            addCriterion("organization_seq >=", value, "organizationSeq");
            return (Criteria) this;
        }

        public Criteria andOrganizationSeqLessThan(String value) {
            addCriterion("organization_seq <", value, "organizationSeq");
            return (Criteria) this;
        }

        public Criteria andOrganizationSeqLessThanOrEqualTo(String value) {
            addCriterion("organization_seq <=", value, "organizationSeq");
            return (Criteria) this;
        }

        public Criteria andOrganizationSeqLike(String value) {
            addCriterion("organization_seq like", value, "organizationSeq");
            return (Criteria) this;
        }

        public Criteria andOrganizationSeqNotLike(String value) {
            addCriterion("organization_seq not like", value, "organizationSeq");
            return (Criteria) this;
        }

        public Criteria andOrganizationSeqIn(List<String> values) {
            addCriterion("organization_seq in", values, "organizationSeq");
            return (Criteria) this;
        }

        public Criteria andOrganizationSeqNotIn(List<String> values) {
            addCriterion("organization_seq not in", values, "organizationSeq");
            return (Criteria) this;
        }

        public Criteria andOrganizationSeqBetween(String value1, String value2) {
            addCriterion("organization_seq between", value1, value2, "organizationSeq");
            return (Criteria) this;
        }

        public Criteria andOrganizationSeqNotBetween(String value1, String value2) {
            addCriterion("organization_seq not between", value1, value2, "organizationSeq");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNull() {
            addCriterion("province is null");
            return (Criteria) this;
        }

        public Criteria andProvinceIsNotNull() {
            addCriterion("province is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceEqualTo(String value) {
            addCriterion("province =", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotEqualTo(String value) {
            addCriterion("province <>", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThan(String value) {
            addCriterion("province >", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("province >=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThan(String value) {
            addCriterion("province <", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLessThanOrEqualTo(String value) {
            addCriterion("province <=", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceLike(String value) {
            addCriterion("province like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotLike(String value) {
            addCriterion("province not like", value, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceIn(List<String> values) {
            addCriterion("province in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotIn(List<String> values) {
            addCriterion("province not in", values, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceBetween(String value1, String value2) {
            addCriterion("province between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andProvinceNotBetween(String value1, String value2) {
            addCriterion("province not between", value1, value2, "province");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("country is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("country is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("country =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("country <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("country >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("country >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("country <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("country <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("country like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("country not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("country in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("country not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("country between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("country not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andTownIsNull() {
            addCriterion("town is null");
            return (Criteria) this;
        }

        public Criteria andTownIsNotNull() {
            addCriterion("town is not null");
            return (Criteria) this;
        }

        public Criteria andTownEqualTo(String value) {
            addCriterion("town =", value, "town");
            return (Criteria) this;
        }

        public Criteria andTownNotEqualTo(String value) {
            addCriterion("town <>", value, "town");
            return (Criteria) this;
        }

        public Criteria andTownGreaterThan(String value) {
            addCriterion("town >", value, "town");
            return (Criteria) this;
        }

        public Criteria andTownGreaterThanOrEqualTo(String value) {
            addCriterion("town >=", value, "town");
            return (Criteria) this;
        }

        public Criteria andTownLessThan(String value) {
            addCriterion("town <", value, "town");
            return (Criteria) this;
        }

        public Criteria andTownLessThanOrEqualTo(String value) {
            addCriterion("town <=", value, "town");
            return (Criteria) this;
        }

        public Criteria andTownLike(String value) {
            addCriterion("town like", value, "town");
            return (Criteria) this;
        }

        public Criteria andTownNotLike(String value) {
            addCriterion("town not like", value, "town");
            return (Criteria) this;
        }

        public Criteria andTownIn(List<String> values) {
            addCriterion("town in", values, "town");
            return (Criteria) this;
        }

        public Criteria andTownNotIn(List<String> values) {
            addCriterion("town not in", values, "town");
            return (Criteria) this;
        }

        public Criteria andTownBetween(String value1, String value2) {
            addCriterion("town between", value1, value2, "town");
            return (Criteria) this;
        }

        public Criteria andTownNotBetween(String value1, String value2) {
            addCriterion("town not between", value1, value2, "town");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Byte value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Byte value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Byte value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Byte value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Byte value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Byte> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Byte> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Byte value1, Byte value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andFamilyCountIsNull() {
            addCriterion("family_count is null");
            return (Criteria) this;
        }

        public Criteria andFamilyCountIsNotNull() {
            addCriterion("family_count is not null");
            return (Criteria) this;
        }

        public Criteria andFamilyCountEqualTo(Integer value) {
            addCriterion("family_count =", value, "familyCount");
            return (Criteria) this;
        }

        public Criteria andFamilyCountNotEqualTo(Integer value) {
            addCriterion("family_count <>", value, "familyCount");
            return (Criteria) this;
        }

        public Criteria andFamilyCountGreaterThan(Integer value) {
            addCriterion("family_count >", value, "familyCount");
            return (Criteria) this;
        }

        public Criteria andFamilyCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("family_count >=", value, "familyCount");
            return (Criteria) this;
        }

        public Criteria andFamilyCountLessThan(Integer value) {
            addCriterion("family_count <", value, "familyCount");
            return (Criteria) this;
        }

        public Criteria andFamilyCountLessThanOrEqualTo(Integer value) {
            addCriterion("family_count <=", value, "familyCount");
            return (Criteria) this;
        }

        public Criteria andFamilyCountIn(List<Integer> values) {
            addCriterion("family_count in", values, "familyCount");
            return (Criteria) this;
        }

        public Criteria andFamilyCountNotIn(List<Integer> values) {
            addCriterion("family_count not in", values, "familyCount");
            return (Criteria) this;
        }

        public Criteria andFamilyCountBetween(Integer value1, Integer value2) {
            addCriterion("family_count between", value1, value2, "familyCount");
            return (Criteria) this;
        }

        public Criteria andFamilyCountNotBetween(Integer value1, Integer value2) {
            addCriterion("family_count not between", value1, value2, "familyCount");
            return (Criteria) this;
        }

        public Criteria andPeopleCountIsNull() {
            addCriterion("people_count is null");
            return (Criteria) this;
        }

        public Criteria andPeopleCountIsNotNull() {
            addCriterion("people_count is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleCountEqualTo(Integer value) {
            addCriterion("people_count =", value, "peopleCount");
            return (Criteria) this;
        }

        public Criteria andPeopleCountNotEqualTo(Integer value) {
            addCriterion("people_count <>", value, "peopleCount");
            return (Criteria) this;
        }

        public Criteria andPeopleCountGreaterThan(Integer value) {
            addCriterion("people_count >", value, "peopleCount");
            return (Criteria) this;
        }

        public Criteria andPeopleCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("people_count >=", value, "peopleCount");
            return (Criteria) this;
        }

        public Criteria andPeopleCountLessThan(Integer value) {
            addCriterion("people_count <", value, "peopleCount");
            return (Criteria) this;
        }

        public Criteria andPeopleCountLessThanOrEqualTo(Integer value) {
            addCriterion("people_count <=", value, "peopleCount");
            return (Criteria) this;
        }

        public Criteria andPeopleCountIn(List<Integer> values) {
            addCriterion("people_count in", values, "peopleCount");
            return (Criteria) this;
        }

        public Criteria andPeopleCountNotIn(List<Integer> values) {
            addCriterion("people_count not in", values, "peopleCount");
            return (Criteria) this;
        }

        public Criteria andPeopleCountBetween(Integer value1, Integer value2) {
            addCriterion("people_count between", value1, value2, "peopleCount");
            return (Criteria) this;
        }

        public Criteria andPeopleCountNotBetween(Integer value1, Integer value2) {
            addCriterion("people_count not between", value1, value2, "peopleCount");
            return (Criteria) this;
        }

        public Criteria andTerminalCountIsNull() {
            addCriterion("terminal_count is null");
            return (Criteria) this;
        }

        public Criteria andTerminalCountIsNotNull() {
            addCriterion("terminal_count is not null");
            return (Criteria) this;
        }

        public Criteria andTerminalCountEqualTo(Integer value) {
            addCriterion("terminal_count =", value, "terminalCount");
            return (Criteria) this;
        }

        public Criteria andTerminalCountNotEqualTo(Integer value) {
            addCriterion("terminal_count <>", value, "terminalCount");
            return (Criteria) this;
        }

        public Criteria andTerminalCountGreaterThan(Integer value) {
            addCriterion("terminal_count >", value, "terminalCount");
            return (Criteria) this;
        }

        public Criteria andTerminalCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("terminal_count >=", value, "terminalCount");
            return (Criteria) this;
        }

        public Criteria andTerminalCountLessThan(Integer value) {
            addCriterion("terminal_count <", value, "terminalCount");
            return (Criteria) this;
        }

        public Criteria andTerminalCountLessThanOrEqualTo(Integer value) {
            addCriterion("terminal_count <=", value, "terminalCount");
            return (Criteria) this;
        }

        public Criteria andTerminalCountIn(List<Integer> values) {
            addCriterion("terminal_count in", values, "terminalCount");
            return (Criteria) this;
        }

        public Criteria andTerminalCountNotIn(List<Integer> values) {
            addCriterion("terminal_count not in", values, "terminalCount");
            return (Criteria) this;
        }

        public Criteria andTerminalCountBetween(Integer value1, Integer value2) {
            addCriterion("terminal_count between", value1, value2, "terminalCount");
            return (Criteria) this;
        }

        public Criteria andTerminalCountNotBetween(Integer value1, Integer value2) {
            addCriterion("terminal_count not between", value1, value2, "terminalCount");
            return (Criteria) this;
        }

        public Criteria andGrandCardCountIsNull() {
            addCriterion("grand_card_count is null");
            return (Criteria) this;
        }

        public Criteria andGrandCardCountIsNotNull() {
            addCriterion("grand_card_count is not null");
            return (Criteria) this;
        }

        public Criteria andGrandCardCountEqualTo(Integer value) {
            addCriterion("grand_card_count =", value, "grandCardCount");
            return (Criteria) this;
        }

        public Criteria andGrandCardCountNotEqualTo(Integer value) {
            addCriterion("grand_card_count <>", value, "grandCardCount");
            return (Criteria) this;
        }

        public Criteria andGrandCardCountGreaterThan(Integer value) {
            addCriterion("grand_card_count >", value, "grandCardCount");
            return (Criteria) this;
        }

        public Criteria andGrandCardCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("grand_card_count >=", value, "grandCardCount");
            return (Criteria) this;
        }

        public Criteria andGrandCardCountLessThan(Integer value) {
            addCriterion("grand_card_count <", value, "grandCardCount");
            return (Criteria) this;
        }

        public Criteria andGrandCardCountLessThanOrEqualTo(Integer value) {
            addCriterion("grand_card_count <=", value, "grandCardCount");
            return (Criteria) this;
        }

        public Criteria andGrandCardCountIn(List<Integer> values) {
            addCriterion("grand_card_count in", values, "grandCardCount");
            return (Criteria) this;
        }

        public Criteria andGrandCardCountNotIn(List<Integer> values) {
            addCriterion("grand_card_count not in", values, "grandCardCount");
            return (Criteria) this;
        }

        public Criteria andGrandCardCountBetween(Integer value1, Integer value2) {
            addCriterion("grand_card_count between", value1, value2, "grandCardCount");
            return (Criteria) this;
        }

        public Criteria andGrandCardCountNotBetween(Integer value1, Integer value2) {
            addCriterion("grand_card_count not between", value1, value2, "grandCardCount");
            return (Criteria) this;
        }

        public Criteria andEnablePromotionActiveIsNull() {
            addCriterion("enable_promotion_active is null");
            return (Criteria) this;
        }

        public Criteria andEnablePromotionActiveIsNotNull() {
            addCriterion("enable_promotion_active is not null");
            return (Criteria) this;
        }

        public Criteria andEnablePromotionActiveEqualTo(Boolean value) {
            addCriterion("enable_promotion_active =", value, "enablePromotionActive");
            return (Criteria) this;
        }

        public Criteria andEnablePromotionActiveNotEqualTo(Boolean value) {
            addCriterion("enable_promotion_active <>", value, "enablePromotionActive");
            return (Criteria) this;
        }

        public Criteria andEnablePromotionActiveGreaterThan(Boolean value) {
            addCriterion("enable_promotion_active >", value, "enablePromotionActive");
            return (Criteria) this;
        }

        public Criteria andEnablePromotionActiveGreaterThanOrEqualTo(Boolean value) {
            addCriterion("enable_promotion_active >=", value, "enablePromotionActive");
            return (Criteria) this;
        }

        public Criteria andEnablePromotionActiveLessThan(Boolean value) {
            addCriterion("enable_promotion_active <", value, "enablePromotionActive");
            return (Criteria) this;
        }

        public Criteria andEnablePromotionActiveLessThanOrEqualTo(Boolean value) {
            addCriterion("enable_promotion_active <=", value, "enablePromotionActive");
            return (Criteria) this;
        }

        public Criteria andEnablePromotionActiveIn(List<Boolean> values) {
            addCriterion("enable_promotion_active in", values, "enablePromotionActive");
            return (Criteria) this;
        }

        public Criteria andEnablePromotionActiveNotIn(List<Boolean> values) {
            addCriterion("enable_promotion_active not in", values, "enablePromotionActive");
            return (Criteria) this;
        }

        public Criteria andEnablePromotionActiveBetween(Boolean value1, Boolean value2) {
            addCriterion("enable_promotion_active between", value1, value2, "enablePromotionActive");
            return (Criteria) this;
        }

        public Criteria andEnablePromotionActiveNotBetween(Boolean value1, Boolean value2) {
            addCriterion("enable_promotion_active not between", value1, value2, "enablePromotionActive");
            return (Criteria) this;
        }

        public Criteria andActiveLocationDetailIsNull() {
            addCriterion("active_location_detail is null");
            return (Criteria) this;
        }

        public Criteria andActiveLocationDetailIsNotNull() {
            addCriterion("active_location_detail is not null");
            return (Criteria) this;
        }

        public Criteria andActiveLocationDetailEqualTo(String value) {
            addCriterion("active_location_detail =", value, "activeLocationDetail");
            return (Criteria) this;
        }

        public Criteria andActiveLocationDetailNotEqualTo(String value) {
            addCriterion("active_location_detail <>", value, "activeLocationDetail");
            return (Criteria) this;
        }

        public Criteria andActiveLocationDetailGreaterThan(String value) {
            addCriterion("active_location_detail >", value, "activeLocationDetail");
            return (Criteria) this;
        }

        public Criteria andActiveLocationDetailGreaterThanOrEqualTo(String value) {
            addCriterion("active_location_detail >=", value, "activeLocationDetail");
            return (Criteria) this;
        }

        public Criteria andActiveLocationDetailLessThan(String value) {
            addCriterion("active_location_detail <", value, "activeLocationDetail");
            return (Criteria) this;
        }

        public Criteria andActiveLocationDetailLessThanOrEqualTo(String value) {
            addCriterion("active_location_detail <=", value, "activeLocationDetail");
            return (Criteria) this;
        }

        public Criteria andActiveLocationDetailLike(String value) {
            addCriterion("active_location_detail like", value, "activeLocationDetail");
            return (Criteria) this;
        }

        public Criteria andActiveLocationDetailNotLike(String value) {
            addCriterion("active_location_detail not like", value, "activeLocationDetail");
            return (Criteria) this;
        }

        public Criteria andActiveLocationDetailIn(List<String> values) {
            addCriterion("active_location_detail in", values, "activeLocationDetail");
            return (Criteria) this;
        }

        public Criteria andActiveLocationDetailNotIn(List<String> values) {
            addCriterion("active_location_detail not in", values, "activeLocationDetail");
            return (Criteria) this;
        }

        public Criteria andActiveLocationDetailBetween(String value1, String value2) {
            addCriterion("active_location_detail between", value1, value2, "activeLocationDetail");
            return (Criteria) this;
        }

        public Criteria andActiveLocationDetailNotBetween(String value1, String value2) {
            addCriterion("active_location_detail not between", value1, value2, "activeLocationDetail");
            return (Criteria) this;
        }

        public Criteria andCommunityTypeIsNull() {
            addCriterion("community_type is null");
            return (Criteria) this;
        }

        public Criteria andCommunityTypeIsNotNull() {
            addCriterion("community_type is not null");
            return (Criteria) this;
        }

        public Criteria andCommunityTypeEqualTo(Integer value) {
            addCriterion("community_type =", value, "communityType");
            return (Criteria) this;
        }

        public Criteria andCommunityTypeNotEqualTo(Integer value) {
            addCriterion("community_type <>", value, "communityType");
            return (Criteria) this;
        }

        public Criteria andCommunityTypeGreaterThan(Integer value) {
            addCriterion("community_type >", value, "communityType");
            return (Criteria) this;
        }

        public Criteria andCommunityTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("community_type >=", value, "communityType");
            return (Criteria) this;
        }

        public Criteria andCommunityTypeLessThan(Integer value) {
            addCriterion("community_type <", value, "communityType");
            return (Criteria) this;
        }

        public Criteria andCommunityTypeLessThanOrEqualTo(Integer value) {
            addCriterion("community_type <=", value, "communityType");
            return (Criteria) this;
        }

        public Criteria andCommunityTypeIn(List<Integer> values) {
            addCriterion("community_type in", values, "communityType");
            return (Criteria) this;
        }

        public Criteria andCommunityTypeNotIn(List<Integer> values) {
            addCriterion("community_type not in", values, "communityType");
            return (Criteria) this;
        }

        public Criteria andCommunityTypeBetween(Integer value1, Integer value2) {
            addCriterion("community_type between", value1, value2, "communityType");
            return (Criteria) this;
        }

        public Criteria andCommunityTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("community_type not between", value1, value2, "communityType");
            return (Criteria) this;
        }

        public Criteria andTranslateStatusIsNull() {
            addCriterion("translate_status is null");
            return (Criteria) this;
        }

        public Criteria andTranslateStatusIsNotNull() {
            addCriterion("translate_status is not null");
            return (Criteria) this;
        }

        public Criteria andTranslateStatusEqualTo(Byte value) {
            addCriterion("translate_status =", value, "translateStatus");
            return (Criteria) this;
        }

        public Criteria andTranslateStatusNotEqualTo(Byte value) {
            addCriterion("translate_status <>", value, "translateStatus");
            return (Criteria) this;
        }

        public Criteria andTranslateStatusGreaterThan(Byte value) {
            addCriterion("translate_status >", value, "translateStatus");
            return (Criteria) this;
        }

        public Criteria andTranslateStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("translate_status >=", value, "translateStatus");
            return (Criteria) this;
        }

        public Criteria andTranslateStatusLessThan(Byte value) {
            addCriterion("translate_status <", value, "translateStatus");
            return (Criteria) this;
        }

        public Criteria andTranslateStatusLessThanOrEqualTo(Byte value) {
            addCriterion("translate_status <=", value, "translateStatus");
            return (Criteria) this;
        }

        public Criteria andTranslateStatusIn(List<Byte> values) {
            addCriterion("translate_status in", values, "translateStatus");
            return (Criteria) this;
        }

        public Criteria andTranslateStatusNotIn(List<Byte> values) {
            addCriterion("translate_status not in", values, "translateStatus");
            return (Criteria) this;
        }

        public Criteria andTranslateStatusBetween(Byte value1, Byte value2) {
            addCriterion("translate_status between", value1, value2, "translateStatus");
            return (Criteria) this;
        }

        public Criteria andTranslateStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("translate_status not between", value1, value2, "translateStatus");
            return (Criteria) this;
        }

        public Criteria andPoiAddressIsNull() {
            addCriterion("poi_address is null");
            return (Criteria) this;
        }

        public Criteria andPoiAddressIsNotNull() {
            addCriterion("poi_address is not null");
            return (Criteria) this;
        }

        public Criteria andPoiAddressEqualTo(String value) {
            addCriterion("poi_address =", value, "poiAddress");
            return (Criteria) this;
        }

        public Criteria andPoiAddressNotEqualTo(String value) {
            addCriterion("poi_address <>", value, "poiAddress");
            return (Criteria) this;
        }

        public Criteria andPoiAddressGreaterThan(String value) {
            addCriterion("poi_address >", value, "poiAddress");
            return (Criteria) this;
        }

        public Criteria andPoiAddressGreaterThanOrEqualTo(String value) {
            addCriterion("poi_address >=", value, "poiAddress");
            return (Criteria) this;
        }

        public Criteria andPoiAddressLessThan(String value) {
            addCriterion("poi_address <", value, "poiAddress");
            return (Criteria) this;
        }

        public Criteria andPoiAddressLessThanOrEqualTo(String value) {
            addCriterion("poi_address <=", value, "poiAddress");
            return (Criteria) this;
        }

        public Criteria andPoiAddressLike(String value) {
            addCriterion("poi_address like", value, "poiAddress");
            return (Criteria) this;
        }

        public Criteria andPoiAddressNotLike(String value) {
            addCriterion("poi_address not like", value, "poiAddress");
            return (Criteria) this;
        }

        public Criteria andPoiAddressIn(List<String> values) {
            addCriterion("poi_address in", values, "poiAddress");
            return (Criteria) this;
        }

        public Criteria andPoiAddressNotIn(List<String> values) {
            addCriterion("poi_address not in", values, "poiAddress");
            return (Criteria) this;
        }

        public Criteria andPoiAddressBetween(String value1, String value2) {
            addCriterion("poi_address between", value1, value2, "poiAddress");
            return (Criteria) this;
        }

        public Criteria andPoiAddressNotBetween(String value1, String value2) {
            addCriterion("poi_address not between", value1, value2, "poiAddress");
            return (Criteria) this;
        }

        public Criteria andBaiduAddressIsNull() {
            addCriterion("baidu_address is null");
            return (Criteria) this;
        }

        public Criteria andBaiduAddressIsNotNull() {
            addCriterion("baidu_address is not null");
            return (Criteria) this;
        }

        public Criteria andBaiduAddressEqualTo(String value) {
            addCriterion("baidu_address =", value, "baiduAddress");
            return (Criteria) this;
        }

        public Criteria andBaiduAddressNotEqualTo(String value) {
            addCriterion("baidu_address <>", value, "baiduAddress");
            return (Criteria) this;
        }

        public Criteria andBaiduAddressGreaterThan(String value) {
            addCriterion("baidu_address >", value, "baiduAddress");
            return (Criteria) this;
        }

        public Criteria andBaiduAddressGreaterThanOrEqualTo(String value) {
            addCriterion("baidu_address >=", value, "baiduAddress");
            return (Criteria) this;
        }

        public Criteria andBaiduAddressLessThan(String value) {
            addCriterion("baidu_address <", value, "baiduAddress");
            return (Criteria) this;
        }

        public Criteria andBaiduAddressLessThanOrEqualTo(String value) {
            addCriterion("baidu_address <=", value, "baiduAddress");
            return (Criteria) this;
        }

        public Criteria andBaiduAddressLike(String value) {
            addCriterion("baidu_address like", value, "baiduAddress");
            return (Criteria) this;
        }

        public Criteria andBaiduAddressNotLike(String value) {
            addCriterion("baidu_address not like", value, "baiduAddress");
            return (Criteria) this;
        }

        public Criteria andBaiduAddressIn(List<String> values) {
            addCriterion("baidu_address in", values, "baiduAddress");
            return (Criteria) this;
        }

        public Criteria andBaiduAddressNotIn(List<String> values) {
            addCriterion("baidu_address not in", values, "baiduAddress");
            return (Criteria) this;
        }

        public Criteria andBaiduAddressBetween(String value1, String value2) {
            addCriterion("baidu_address between", value1, value2, "baiduAddress");
            return (Criteria) this;
        }

        public Criteria andBaiduAddressNotBetween(String value1, String value2) {
            addCriterion("baidu_address not between", value1, value2, "baiduAddress");
            return (Criteria) this;
        }

        public Criteria andIsJoinSdkIsNull() {
            addCriterion("is_join_sdk is null");
            return (Criteria) this;
        }

        public Criteria andIsJoinSdkIsNotNull() {
            addCriterion("is_join_sdk is not null");
            return (Criteria) this;
        }

        public Criteria andIsJoinSdkEqualTo(Boolean value) {
            addCriterion("is_join_sdk =", value, "isJoinSdk");
            return (Criteria) this;
        }

        public Criteria andIsJoinSdkNotEqualTo(Boolean value) {
            addCriterion("is_join_sdk <>", value, "isJoinSdk");
            return (Criteria) this;
        }

        public Criteria andIsJoinSdkGreaterThan(Boolean value) {
            addCriterion("is_join_sdk >", value, "isJoinSdk");
            return (Criteria) this;
        }

        public Criteria andIsJoinSdkGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_join_sdk >=", value, "isJoinSdk");
            return (Criteria) this;
        }

        public Criteria andIsJoinSdkLessThan(Boolean value) {
            addCriterion("is_join_sdk <", value, "isJoinSdk");
            return (Criteria) this;
        }

        public Criteria andIsJoinSdkLessThanOrEqualTo(Boolean value) {
            addCriterion("is_join_sdk <=", value, "isJoinSdk");
            return (Criteria) this;
        }

        public Criteria andIsJoinSdkIn(List<Boolean> values) {
            addCriterion("is_join_sdk in", values, "isJoinSdk");
            return (Criteria) this;
        }

        public Criteria andIsJoinSdkNotIn(List<Boolean> values) {
            addCriterion("is_join_sdk not in", values, "isJoinSdk");
            return (Criteria) this;
        }

        public Criteria andIsJoinSdkBetween(Boolean value1, Boolean value2) {
            addCriterion("is_join_sdk between", value1, value2, "isJoinSdk");
            return (Criteria) this;
        }

        public Criteria andIsJoinSdkNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_join_sdk not between", value1, value2, "isJoinSdk");
            return (Criteria) this;
        }

        public Criteria andIsUImportIsNull() {
            addCriterion("is_u_import is null");
            return (Criteria) this;
        }

        public Criteria andIsUImportIsNotNull() {
            addCriterion("is_u_import is not null");
            return (Criteria) this;
        }

        public Criteria andIsUImportEqualTo(Boolean value) {
            addCriterion("is_u_import =", value, "isUImport");
            return (Criteria) this;
        }

        public Criteria andIsUImportNotEqualTo(Boolean value) {
            addCriterion("is_u_import <>", value, "isUImport");
            return (Criteria) this;
        }

        public Criteria andIsUImportGreaterThan(Boolean value) {
            addCriterion("is_u_import >", value, "isUImport");
            return (Criteria) this;
        }

        public Criteria andIsUImportGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_u_import >=", value, "isUImport");
            return (Criteria) this;
        }

        public Criteria andIsUImportLessThan(Boolean value) {
            addCriterion("is_u_import <", value, "isUImport");
            return (Criteria) this;
        }

        public Criteria andIsUImportLessThanOrEqualTo(Boolean value) {
            addCriterion("is_u_import <=", value, "isUImport");
            return (Criteria) this;
        }

        public Criteria andIsUImportIn(List<Boolean> values) {
            addCriterion("is_u_import in", values, "isUImport");
            return (Criteria) this;
        }

        public Criteria andIsUImportNotIn(List<Boolean> values) {
            addCriterion("is_u_import not in", values, "isUImport");
            return (Criteria) this;
        }

        public Criteria andIsUImportBetween(Boolean value1, Boolean value2) {
            addCriterion("is_u_import between", value1, value2, "isUImport");
            return (Criteria) this;
        }

        public Criteria andIsUImportNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_u_import not between", value1, value2, "isUImport");
            return (Criteria) this;
        }

        public Criteria andMediaTypeIsNull() {
            addCriterion("media_type is null");
            return (Criteria) this;
        }

        public Criteria andMediaTypeIsNotNull() {
            addCriterion("media_type is not null");
            return (Criteria) this;
        }

        public Criteria andMediaTypeEqualTo(Short value) {
            addCriterion("media_type =", value, "mediaType");
            return (Criteria) this;
        }

        public Criteria andMediaTypeNotEqualTo(Short value) {
            addCriterion("media_type <>", value, "mediaType");
            return (Criteria) this;
        }

        public Criteria andMediaTypeGreaterThan(Short value) {
            addCriterion("media_type >", value, "mediaType");
            return (Criteria) this;
        }

        public Criteria andMediaTypeGreaterThanOrEqualTo(Short value) {
            addCriterion("media_type >=", value, "mediaType");
            return (Criteria) this;
        }

        public Criteria andMediaTypeLessThan(Short value) {
            addCriterion("media_type <", value, "mediaType");
            return (Criteria) this;
        }

        public Criteria andMediaTypeLessThanOrEqualTo(Short value) {
            addCriterion("media_type <=", value, "mediaType");
            return (Criteria) this;
        }

        public Criteria andMediaTypeIn(List<Short> values) {
            addCriterion("media_type in", values, "mediaType");
            return (Criteria) this;
        }

        public Criteria andMediaTypeNotIn(List<Short> values) {
            addCriterion("media_type not in", values, "mediaType");
            return (Criteria) this;
        }

        public Criteria andMediaTypeBetween(Short value1, Short value2) {
            addCriterion("media_type between", value1, value2, "mediaType");
            return (Criteria) this;
        }

        public Criteria andMediaTypeNotBetween(Short value1, Short value2) {
            addCriterion("media_type not between", value1, value2, "mediaType");
            return (Criteria) this;
        }

        public Criteria andMediaCompanyNameIsNull() {
            addCriterion("media_company_name is null");
            return (Criteria) this;
        }

        public Criteria andMediaCompanyNameIsNotNull() {
            addCriterion("media_company_name is not null");
            return (Criteria) this;
        }

        public Criteria andMediaCompanyNameEqualTo(String value) {
            addCriterion("media_company_name =", value, "mediaCompanyName");
            return (Criteria) this;
        }

        public Criteria andMediaCompanyNameNotEqualTo(String value) {
            addCriterion("media_company_name <>", value, "mediaCompanyName");
            return (Criteria) this;
        }

        public Criteria andMediaCompanyNameGreaterThan(String value) {
            addCriterion("media_company_name >", value, "mediaCompanyName");
            return (Criteria) this;
        }

        public Criteria andMediaCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("media_company_name >=", value, "mediaCompanyName");
            return (Criteria) this;
        }

        public Criteria andMediaCompanyNameLessThan(String value) {
            addCriterion("media_company_name <", value, "mediaCompanyName");
            return (Criteria) this;
        }

        public Criteria andMediaCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("media_company_name <=", value, "mediaCompanyName");
            return (Criteria) this;
        }

        public Criteria andMediaCompanyNameLike(String value) {
            addCriterion("media_company_name like", value, "mediaCompanyName");
            return (Criteria) this;
        }

        public Criteria andMediaCompanyNameNotLike(String value) {
            addCriterion("media_company_name not like", value, "mediaCompanyName");
            return (Criteria) this;
        }

        public Criteria andMediaCompanyNameIn(List<String> values) {
            addCriterion("media_company_name in", values, "mediaCompanyName");
            return (Criteria) this;
        }

        public Criteria andMediaCompanyNameNotIn(List<String> values) {
            addCriterion("media_company_name not in", values, "mediaCompanyName");
            return (Criteria) this;
        }

        public Criteria andMediaCompanyNameBetween(String value1, String value2) {
            addCriterion("media_company_name between", value1, value2, "mediaCompanyName");
            return (Criteria) this;
        }

        public Criteria andMediaCompanyNameNotBetween(String value1, String value2) {
            addCriterion("media_company_name not between", value1, value2, "mediaCompanyName");
            return (Criteria) this;
        }

        public Criteria andMediaAppIdIsNull() {
            addCriterion("media_app_id is null");
            return (Criteria) this;
        }

        public Criteria andMediaAppIdIsNotNull() {
            addCriterion("media_app_id is not null");
            return (Criteria) this;
        }

        public Criteria andMediaAppIdEqualTo(String value) {
            addCriterion("media_app_id =", value, "mediaAppId");
            return (Criteria) this;
        }

        public Criteria andMediaAppIdNotEqualTo(String value) {
            addCriterion("media_app_id <>", value, "mediaAppId");
            return (Criteria) this;
        }

        public Criteria andMediaAppIdGreaterThan(String value) {
            addCriterion("media_app_id >", value, "mediaAppId");
            return (Criteria) this;
        }

        public Criteria andMediaAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("media_app_id >=", value, "mediaAppId");
            return (Criteria) this;
        }

        public Criteria andMediaAppIdLessThan(String value) {
            addCriterion("media_app_id <", value, "mediaAppId");
            return (Criteria) this;
        }

        public Criteria andMediaAppIdLessThanOrEqualTo(String value) {
            addCriterion("media_app_id <=", value, "mediaAppId");
            return (Criteria) this;
        }

        public Criteria andMediaAppIdLike(String value) {
            addCriterion("media_app_id like", value, "mediaAppId");
            return (Criteria) this;
        }

        public Criteria andMediaAppIdNotLike(String value) {
            addCriterion("media_app_id not like", value, "mediaAppId");
            return (Criteria) this;
        }

        public Criteria andMediaAppIdIn(List<String> values) {
            addCriterion("media_app_id in", values, "mediaAppId");
            return (Criteria) this;
        }

        public Criteria andMediaAppIdNotIn(List<String> values) {
            addCriterion("media_app_id not in", values, "mediaAppId");
            return (Criteria) this;
        }

        public Criteria andMediaAppIdBetween(String value1, String value2) {
            addCriterion("media_app_id between", value1, value2, "mediaAppId");
            return (Criteria) this;
        }

        public Criteria andMediaAppIdNotBetween(String value1, String value2) {
            addCriterion("media_app_id not between", value1, value2, "mediaAppId");
            return (Criteria) this;
        }

        public Criteria andUnionIdIsNull() {
            addCriterion("union_id is null");
            return (Criteria) this;
        }

        public Criteria andUnionIdIsNotNull() {
            addCriterion("union_id is not null");
            return (Criteria) this;
        }

        public Criteria andUnionIdEqualTo(String value) {
            addCriterion("union_id =", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdNotEqualTo(String value) {
            addCriterion("union_id <>", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdGreaterThan(String value) {
            addCriterion("union_id >", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdGreaterThanOrEqualTo(String value) {
            addCriterion("union_id >=", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdLessThan(String value) {
            addCriterion("union_id <", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdLessThanOrEqualTo(String value) {
            addCriterion("union_id <=", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdLike(String value) {
            addCriterion("union_id like", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdNotLike(String value) {
            addCriterion("union_id not like", value, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdIn(List<String> values) {
            addCriterion("union_id in", values, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdNotIn(List<String> values) {
            addCriterion("union_id not in", values, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdBetween(String value1, String value2) {
            addCriterion("union_id between", value1, value2, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionIdNotBetween(String value1, String value2) {
            addCriterion("union_id not between", value1, value2, "unionId");
            return (Criteria) this;
        }

        public Criteria andUnionNameIsNull() {
            addCriterion("union_name is null");
            return (Criteria) this;
        }

        public Criteria andUnionNameIsNotNull() {
            addCriterion("union_name is not null");
            return (Criteria) this;
        }

        public Criteria andUnionNameEqualTo(String value) {
            addCriterion("union_name =", value, "unionName");
            return (Criteria) this;
        }

        public Criteria andUnionNameNotEqualTo(String value) {
            addCriterion("union_name <>", value, "unionName");
            return (Criteria) this;
        }

        public Criteria andUnionNameGreaterThan(String value) {
            addCriterion("union_name >", value, "unionName");
            return (Criteria) this;
        }

        public Criteria andUnionNameGreaterThanOrEqualTo(String value) {
            addCriterion("union_name >=", value, "unionName");
            return (Criteria) this;
        }

        public Criteria andUnionNameLessThan(String value) {
            addCriterion("union_name <", value, "unionName");
            return (Criteria) this;
        }

        public Criteria andUnionNameLessThanOrEqualTo(String value) {
            addCriterion("union_name <=", value, "unionName");
            return (Criteria) this;
        }

        public Criteria andUnionNameLike(String value) {
            addCriterion("union_name like", value, "unionName");
            return (Criteria) this;
        }

        public Criteria andUnionNameNotLike(String value) {
            addCriterion("union_name not like", value, "unionName");
            return (Criteria) this;
        }

        public Criteria andUnionNameIn(List<String> values) {
            addCriterion("union_name in", values, "unionName");
            return (Criteria) this;
        }

        public Criteria andUnionNameNotIn(List<String> values) {
            addCriterion("union_name not in", values, "unionName");
            return (Criteria) this;
        }

        public Criteria andUnionNameBetween(String value1, String value2) {
            addCriterion("union_name between", value1, value2, "unionName");
            return (Criteria) this;
        }

        public Criteria andUnionNameNotBetween(String value1, String value2) {
            addCriterion("union_name not between", value1, value2, "unionName");
            return (Criteria) this;
        }

        public Criteria andResolutionXIsNull() {
            addCriterion("resolution_x is null");
            return (Criteria) this;
        }

        public Criteria andResolutionXIsNotNull() {
            addCriterion("resolution_x is not null");
            return (Criteria) this;
        }

        public Criteria andResolutionXEqualTo(String value) {
            addCriterion("resolution_x =", value, "resolutionX");
            return (Criteria) this;
        }

        public Criteria andResolutionXNotEqualTo(String value) {
            addCriterion("resolution_x <>", value, "resolutionX");
            return (Criteria) this;
        }

        public Criteria andResolutionXGreaterThan(String value) {
            addCriterion("resolution_x >", value, "resolutionX");
            return (Criteria) this;
        }

        public Criteria andResolutionXGreaterThanOrEqualTo(String value) {
            addCriterion("resolution_x >=", value, "resolutionX");
            return (Criteria) this;
        }

        public Criteria andResolutionXLessThan(String value) {
            addCriterion("resolution_x <", value, "resolutionX");
            return (Criteria) this;
        }

        public Criteria andResolutionXLessThanOrEqualTo(String value) {
            addCriterion("resolution_x <=", value, "resolutionX");
            return (Criteria) this;
        }

        public Criteria andResolutionXLike(String value) {
            addCriterion("resolution_x like", value, "resolutionX");
            return (Criteria) this;
        }

        public Criteria andResolutionXNotLike(String value) {
            addCriterion("resolution_x not like", value, "resolutionX");
            return (Criteria) this;
        }

        public Criteria andResolutionXIn(List<String> values) {
            addCriterion("resolution_x in", values, "resolutionX");
            return (Criteria) this;
        }

        public Criteria andResolutionXNotIn(List<String> values) {
            addCriterion("resolution_x not in", values, "resolutionX");
            return (Criteria) this;
        }

        public Criteria andResolutionXBetween(String value1, String value2) {
            addCriterion("resolution_x between", value1, value2, "resolutionX");
            return (Criteria) this;
        }

        public Criteria andResolutionXNotBetween(String value1, String value2) {
            addCriterion("resolution_x not between", value1, value2, "resolutionX");
            return (Criteria) this;
        }

        public Criteria andResolutionYIsNull() {
            addCriterion("resolution_y is null");
            return (Criteria) this;
        }

        public Criteria andResolutionYIsNotNull() {
            addCriterion("resolution_y is not null");
            return (Criteria) this;
        }

        public Criteria andResolutionYEqualTo(String value) {
            addCriterion("resolution_y =", value, "resolutionY");
            return (Criteria) this;
        }

        public Criteria andResolutionYNotEqualTo(String value) {
            addCriterion("resolution_y <>", value, "resolutionY");
            return (Criteria) this;
        }

        public Criteria andResolutionYGreaterThan(String value) {
            addCriterion("resolution_y >", value, "resolutionY");
            return (Criteria) this;
        }

        public Criteria andResolutionYGreaterThanOrEqualTo(String value) {
            addCriterion("resolution_y >=", value, "resolutionY");
            return (Criteria) this;
        }

        public Criteria andResolutionYLessThan(String value) {
            addCriterion("resolution_y <", value, "resolutionY");
            return (Criteria) this;
        }

        public Criteria andResolutionYLessThanOrEqualTo(String value) {
            addCriterion("resolution_y <=", value, "resolutionY");
            return (Criteria) this;
        }

        public Criteria andResolutionYLike(String value) {
            addCriterion("resolution_y like", value, "resolutionY");
            return (Criteria) this;
        }

        public Criteria andResolutionYNotLike(String value) {
            addCriterion("resolution_y not like", value, "resolutionY");
            return (Criteria) this;
        }

        public Criteria andResolutionYIn(List<String> values) {
            addCriterion("resolution_y in", values, "resolutionY");
            return (Criteria) this;
        }

        public Criteria andResolutionYNotIn(List<String> values) {
            addCriterion("resolution_y not in", values, "resolutionY");
            return (Criteria) this;
        }

        public Criteria andResolutionYBetween(String value1, String value2) {
            addCriterion("resolution_y between", value1, value2, "resolutionY");
            return (Criteria) this;
        }

        public Criteria andResolutionYNotBetween(String value1, String value2) {
            addCriterion("resolution_y not between", value1, value2, "resolutionY");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table community
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table community
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}