server:
  servlet:
    context-path: /demo-mybatis
  port: 80
##数据库 datasource配置
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/adms?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: wsrp
    password: jl2012
    type: com.alibaba.druid.pool.DruidDataSource #数据库连接池
#mybatis配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
