server:
  servlet:
    context-path: /demo-mybatis
  port: 9999
##数据库 datasource配置
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/mytest?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource #数据库连接池
#mybatis配置
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
#答应mybatis日志
logging:
  level:
    com:
     gzzsc:
       lai:
         mapper: debug

