package com.gzzsc.lai.entity;

import java.io.Serializable;

public class UnionInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column union_info.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column union_info.app_id
     *
     * @mbggenerated
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column union_info.app_key
     *
     * @mbggenerated
     */
    private String appKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column union_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column union_info.on_off
     *
     * @mbggenerated
     */
    private Boolean onOff;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column union_info.req_url
     *
     * @mbggenerated
     */
    private String reqUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column union_info.report_url
     *
     * @mbggenerated
     */
    private String reportUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column union_info.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column union_info.sn
     *
     * @mbggenerated
     */
    private Integer sn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column union_info.material_audit_url
     *
     * @mbggenerated
     */
    private String materialAuditUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column union_info.my_app_id
     *
     * @mbggenerated
     */
    private String myAppId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column union_info.my_app_key
     *
     * @mbggenerated
     */
    private String myAppKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column union_info.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column union_info.count
     *
     * @mbggenerated
     */
    private Integer count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column union_info.up_mate_url
     *
     * @mbggenerated
     */
    private String upMateUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column union_info.free_audit
     *
     * @mbggenerated
     */
    private Integer freeAudit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column union_info.id
     *
     * @return the value of union_info.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column union_info.id
     *
     * @param id the value for union_info.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column union_info.app_id
     *
     * @return the value of union_info.app_id
     *
     * @mbggenerated
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column union_info.app_id
     *
     * @param appId the value for union_info.app_id
     *
     * @mbggenerated
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column union_info.app_key
     *
     * @return the value of union_info.app_key
     *
     * @mbggenerated
     */
    public String getAppKey() {
        return appKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column union_info.app_key
     *
     * @param appKey the value for union_info.app_key
     *
     * @mbggenerated
     */
    public void setAppKey(String appKey) {
        this.appKey = appKey == null ? null : appKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column union_info.name
     *
     * @return the value of union_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column union_info.name
     *
     * @param name the value for union_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column union_info.on_off
     *
     * @return the value of union_info.on_off
     *
     * @mbggenerated
     */
    public Boolean getOnOff() {
        return onOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column union_info.on_off
     *
     * @param onOff the value for union_info.on_off
     *
     * @mbggenerated
     */
    public void setOnOff(Boolean onOff) {
        this.onOff = onOff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column union_info.req_url
     *
     * @return the value of union_info.req_url
     *
     * @mbggenerated
     */
    public String getReqUrl() {
        return reqUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column union_info.req_url
     *
     * @param reqUrl the value for union_info.req_url
     *
     * @mbggenerated
     */
    public void setReqUrl(String reqUrl) {
        this.reqUrl = reqUrl == null ? null : reqUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column union_info.report_url
     *
     * @return the value of union_info.report_url
     *
     * @mbggenerated
     */
    public String getReportUrl() {
        return reportUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column union_info.report_url
     *
     * @param reportUrl the value for union_info.report_url
     *
     * @mbggenerated
     */
    public void setReportUrl(String reportUrl) {
        this.reportUrl = reportUrl == null ? null : reportUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column union_info.remark
     *
     * @return the value of union_info.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column union_info.remark
     *
     * @param remark the value for union_info.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column union_info.sn
     *
     * @return the value of union_info.sn
     *
     * @mbggenerated
     */
    public Integer getSn() {
        return sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column union_info.sn
     *
     * @param sn the value for union_info.sn
     *
     * @mbggenerated
     */
    public void setSn(Integer sn) {
        this.sn = sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column union_info.material_audit_url
     *
     * @return the value of union_info.material_audit_url
     *
     * @mbggenerated
     */
    public String getMaterialAuditUrl() {
        return materialAuditUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column union_info.material_audit_url
     *
     * @param materialAuditUrl the value for union_info.material_audit_url
     *
     * @mbggenerated
     */
    public void setMaterialAuditUrl(String materialAuditUrl) {
        this.materialAuditUrl = materialAuditUrl == null ? null : materialAuditUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column union_info.my_app_id
     *
     * @return the value of union_info.my_app_id
     *
     * @mbggenerated
     */
    public String getMyAppId() {
        return myAppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column union_info.my_app_id
     *
     * @param myAppId the value for union_info.my_app_id
     *
     * @mbggenerated
     */
    public void setMyAppId(String myAppId) {
        this.myAppId = myAppId == null ? null : myAppId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column union_info.my_app_key
     *
     * @return the value of union_info.my_app_key
     *
     * @mbggenerated
     */
    public String getMyAppKey() {
        return myAppKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column union_info.my_app_key
     *
     * @param myAppKey the value for union_info.my_app_key
     *
     * @mbggenerated
     */
    public void setMyAppKey(String myAppKey) {
        this.myAppKey = myAppKey == null ? null : myAppKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column union_info.code
     *
     * @return the value of union_info.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column union_info.code
     *
     * @param code the value for union_info.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column union_info.count
     *
     * @return the value of union_info.count
     *
     * @mbggenerated
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column union_info.count
     *
     * @param count the value for union_info.count
     *
     * @mbggenerated
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column union_info.up_mate_url
     *
     * @return the value of union_info.up_mate_url
     *
     * @mbggenerated
     */
    public String getUpMateUrl() {
        return upMateUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column union_info.up_mate_url
     *
     * @param upMateUrl the value for union_info.up_mate_url
     *
     * @mbggenerated
     */
    public void setUpMateUrl(String upMateUrl) {
        this.upMateUrl = upMateUrl == null ? null : upMateUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column union_info.free_audit
     *
     * @return the value of union_info.free_audit
     *
     * @mbggenerated
     */
    public Integer getFreeAudit() {
        return freeAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column union_info.free_audit
     *
     * @param freeAudit the value for union_info.free_audit
     *
     * @mbggenerated
     */
    public void setFreeAudit(Integer freeAudit) {
        this.freeAudit = freeAudit;
    }
}