package com.gzzsc.lai.entity;

import java.util.ArrayList;
import java.util.List;

public class UnionInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table union_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table union_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table union_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_info
     *
     * @mbggenerated
     */
    public UnionInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table union_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table union_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("app_id like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("app_id not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppKeyIsNull() {
            addCriterion("app_key is null");
            return (Criteria) this;
        }

        public Criteria andAppKeyIsNotNull() {
            addCriterion("app_key is not null");
            return (Criteria) this;
        }

        public Criteria andAppKeyEqualTo(String value) {
            addCriterion("app_key =", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotEqualTo(String value) {
            addCriterion("app_key <>", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyGreaterThan(String value) {
            addCriterion("app_key >", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyGreaterThanOrEqualTo(String value) {
            addCriterion("app_key >=", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyLessThan(String value) {
            addCriterion("app_key <", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyLessThanOrEqualTo(String value) {
            addCriterion("app_key <=", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyLike(String value) {
            addCriterion("app_key like", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotLike(String value) {
            addCriterion("app_key not like", value, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyIn(List<String> values) {
            addCriterion("app_key in", values, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotIn(List<String> values) {
            addCriterion("app_key not in", values, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyBetween(String value1, String value2) {
            addCriterion("app_key between", value1, value2, "appKey");
            return (Criteria) this;
        }

        public Criteria andAppKeyNotBetween(String value1, String value2) {
            addCriterion("app_key not between", value1, value2, "appKey");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andOnOffIsNull() {
            addCriterion("on_off is null");
            return (Criteria) this;
        }

        public Criteria andOnOffIsNotNull() {
            addCriterion("on_off is not null");
            return (Criteria) this;
        }

        public Criteria andOnOffEqualTo(Boolean value) {
            addCriterion("on_off =", value, "onOff");
            return (Criteria) this;
        }

        public Criteria andOnOffNotEqualTo(Boolean value) {
            addCriterion("on_off <>", value, "onOff");
            return (Criteria) this;
        }

        public Criteria andOnOffGreaterThan(Boolean value) {
            addCriterion("on_off >", value, "onOff");
            return (Criteria) this;
        }

        public Criteria andOnOffGreaterThanOrEqualTo(Boolean value) {
            addCriterion("on_off >=", value, "onOff");
            return (Criteria) this;
        }

        public Criteria andOnOffLessThan(Boolean value) {
            addCriterion("on_off <", value, "onOff");
            return (Criteria) this;
        }

        public Criteria andOnOffLessThanOrEqualTo(Boolean value) {
            addCriterion("on_off <=", value, "onOff");
            return (Criteria) this;
        }

        public Criteria andOnOffIn(List<Boolean> values) {
            addCriterion("on_off in", values, "onOff");
            return (Criteria) this;
        }

        public Criteria andOnOffNotIn(List<Boolean> values) {
            addCriterion("on_off not in", values, "onOff");
            return (Criteria) this;
        }

        public Criteria andOnOffBetween(Boolean value1, Boolean value2) {
            addCriterion("on_off between", value1, value2, "onOff");
            return (Criteria) this;
        }

        public Criteria andOnOffNotBetween(Boolean value1, Boolean value2) {
            addCriterion("on_off not between", value1, value2, "onOff");
            return (Criteria) this;
        }

        public Criteria andReqUrlIsNull() {
            addCriterion("req_url is null");
            return (Criteria) this;
        }

        public Criteria andReqUrlIsNotNull() {
            addCriterion("req_url is not null");
            return (Criteria) this;
        }

        public Criteria andReqUrlEqualTo(String value) {
            addCriterion("req_url =", value, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlNotEqualTo(String value) {
            addCriterion("req_url <>", value, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlGreaterThan(String value) {
            addCriterion("req_url >", value, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlGreaterThanOrEqualTo(String value) {
            addCriterion("req_url >=", value, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlLessThan(String value) {
            addCriterion("req_url <", value, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlLessThanOrEqualTo(String value) {
            addCriterion("req_url <=", value, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlLike(String value) {
            addCriterion("req_url like", value, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlNotLike(String value) {
            addCriterion("req_url not like", value, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlIn(List<String> values) {
            addCriterion("req_url in", values, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlNotIn(List<String> values) {
            addCriterion("req_url not in", values, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlBetween(String value1, String value2) {
            addCriterion("req_url between", value1, value2, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReqUrlNotBetween(String value1, String value2) {
            addCriterion("req_url not between", value1, value2, "reqUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlIsNull() {
            addCriterion("report_url is null");
            return (Criteria) this;
        }

        public Criteria andReportUrlIsNotNull() {
            addCriterion("report_url is not null");
            return (Criteria) this;
        }

        public Criteria andReportUrlEqualTo(String value) {
            addCriterion("report_url =", value, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlNotEqualTo(String value) {
            addCriterion("report_url <>", value, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlGreaterThan(String value) {
            addCriterion("report_url >", value, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlGreaterThanOrEqualTo(String value) {
            addCriterion("report_url >=", value, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlLessThan(String value) {
            addCriterion("report_url <", value, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlLessThanOrEqualTo(String value) {
            addCriterion("report_url <=", value, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlLike(String value) {
            addCriterion("report_url like", value, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlNotLike(String value) {
            addCriterion("report_url not like", value, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlIn(List<String> values) {
            addCriterion("report_url in", values, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlNotIn(List<String> values) {
            addCriterion("report_url not in", values, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlBetween(String value1, String value2) {
            addCriterion("report_url between", value1, value2, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andReportUrlNotBetween(String value1, String value2) {
            addCriterion("report_url not between", value1, value2, "reportUrl");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andSnIsNull() {
            addCriterion("sn is null");
            return (Criteria) this;
        }

        public Criteria andSnIsNotNull() {
            addCriterion("sn is not null");
            return (Criteria) this;
        }

        public Criteria andSnEqualTo(Integer value) {
            addCriterion("sn =", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotEqualTo(Integer value) {
            addCriterion("sn <>", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnGreaterThan(Integer value) {
            addCriterion("sn >", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnGreaterThanOrEqualTo(Integer value) {
            addCriterion("sn >=", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLessThan(Integer value) {
            addCriterion("sn <", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnLessThanOrEqualTo(Integer value) {
            addCriterion("sn <=", value, "sn");
            return (Criteria) this;
        }

        public Criteria andSnIn(List<Integer> values) {
            addCriterion("sn in", values, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotIn(List<Integer> values) {
            addCriterion("sn not in", values, "sn");
            return (Criteria) this;
        }

        public Criteria andSnBetween(Integer value1, Integer value2) {
            addCriterion("sn between", value1, value2, "sn");
            return (Criteria) this;
        }

        public Criteria andSnNotBetween(Integer value1, Integer value2) {
            addCriterion("sn not between", value1, value2, "sn");
            return (Criteria) this;
        }

        public Criteria andMaterialAuditUrlIsNull() {
            addCriterion("material_audit_url is null");
            return (Criteria) this;
        }

        public Criteria andMaterialAuditUrlIsNotNull() {
            addCriterion("material_audit_url is not null");
            return (Criteria) this;
        }

        public Criteria andMaterialAuditUrlEqualTo(String value) {
            addCriterion("material_audit_url =", value, "materialAuditUrl");
            return (Criteria) this;
        }

        public Criteria andMaterialAuditUrlNotEqualTo(String value) {
            addCriterion("material_audit_url <>", value, "materialAuditUrl");
            return (Criteria) this;
        }

        public Criteria andMaterialAuditUrlGreaterThan(String value) {
            addCriterion("material_audit_url >", value, "materialAuditUrl");
            return (Criteria) this;
        }

        public Criteria andMaterialAuditUrlGreaterThanOrEqualTo(String value) {
            addCriterion("material_audit_url >=", value, "materialAuditUrl");
            return (Criteria) this;
        }

        public Criteria andMaterialAuditUrlLessThan(String value) {
            addCriterion("material_audit_url <", value, "materialAuditUrl");
            return (Criteria) this;
        }

        public Criteria andMaterialAuditUrlLessThanOrEqualTo(String value) {
            addCriterion("material_audit_url <=", value, "materialAuditUrl");
            return (Criteria) this;
        }

        public Criteria andMaterialAuditUrlLike(String value) {
            addCriterion("material_audit_url like", value, "materialAuditUrl");
            return (Criteria) this;
        }

        public Criteria andMaterialAuditUrlNotLike(String value) {
            addCriterion("material_audit_url not like", value, "materialAuditUrl");
            return (Criteria) this;
        }

        public Criteria andMaterialAuditUrlIn(List<String> values) {
            addCriterion("material_audit_url in", values, "materialAuditUrl");
            return (Criteria) this;
        }

        public Criteria andMaterialAuditUrlNotIn(List<String> values) {
            addCriterion("material_audit_url not in", values, "materialAuditUrl");
            return (Criteria) this;
        }

        public Criteria andMaterialAuditUrlBetween(String value1, String value2) {
            addCriterion("material_audit_url between", value1, value2, "materialAuditUrl");
            return (Criteria) this;
        }

        public Criteria andMaterialAuditUrlNotBetween(String value1, String value2) {
            addCriterion("material_audit_url not between", value1, value2, "materialAuditUrl");
            return (Criteria) this;
        }

        public Criteria andMyAppIdIsNull() {
            addCriterion("my_app_id is null");
            return (Criteria) this;
        }

        public Criteria andMyAppIdIsNotNull() {
            addCriterion("my_app_id is not null");
            return (Criteria) this;
        }

        public Criteria andMyAppIdEqualTo(String value) {
            addCriterion("my_app_id =", value, "myAppId");
            return (Criteria) this;
        }

        public Criteria andMyAppIdNotEqualTo(String value) {
            addCriterion("my_app_id <>", value, "myAppId");
            return (Criteria) this;
        }

        public Criteria andMyAppIdGreaterThan(String value) {
            addCriterion("my_app_id >", value, "myAppId");
            return (Criteria) this;
        }

        public Criteria andMyAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("my_app_id >=", value, "myAppId");
            return (Criteria) this;
        }

        public Criteria andMyAppIdLessThan(String value) {
            addCriterion("my_app_id <", value, "myAppId");
            return (Criteria) this;
        }

        public Criteria andMyAppIdLessThanOrEqualTo(String value) {
            addCriterion("my_app_id <=", value, "myAppId");
            return (Criteria) this;
        }

        public Criteria andMyAppIdLike(String value) {
            addCriterion("my_app_id like", value, "myAppId");
            return (Criteria) this;
        }

        public Criteria andMyAppIdNotLike(String value) {
            addCriterion("my_app_id not like", value, "myAppId");
            return (Criteria) this;
        }

        public Criteria andMyAppIdIn(List<String> values) {
            addCriterion("my_app_id in", values, "myAppId");
            return (Criteria) this;
        }

        public Criteria andMyAppIdNotIn(List<String> values) {
            addCriterion("my_app_id not in", values, "myAppId");
            return (Criteria) this;
        }

        public Criteria andMyAppIdBetween(String value1, String value2) {
            addCriterion("my_app_id between", value1, value2, "myAppId");
            return (Criteria) this;
        }

        public Criteria andMyAppIdNotBetween(String value1, String value2) {
            addCriterion("my_app_id not between", value1, value2, "myAppId");
            return (Criteria) this;
        }

        public Criteria andMyAppKeyIsNull() {
            addCriterion("my_app_key is null");
            return (Criteria) this;
        }

        public Criteria andMyAppKeyIsNotNull() {
            addCriterion("my_app_key is not null");
            return (Criteria) this;
        }

        public Criteria andMyAppKeyEqualTo(String value) {
            addCriterion("my_app_key =", value, "myAppKey");
            return (Criteria) this;
        }

        public Criteria andMyAppKeyNotEqualTo(String value) {
            addCriterion("my_app_key <>", value, "myAppKey");
            return (Criteria) this;
        }

        public Criteria andMyAppKeyGreaterThan(String value) {
            addCriterion("my_app_key >", value, "myAppKey");
            return (Criteria) this;
        }

        public Criteria andMyAppKeyGreaterThanOrEqualTo(String value) {
            addCriterion("my_app_key >=", value, "myAppKey");
            return (Criteria) this;
        }

        public Criteria andMyAppKeyLessThan(String value) {
            addCriterion("my_app_key <", value, "myAppKey");
            return (Criteria) this;
        }

        public Criteria andMyAppKeyLessThanOrEqualTo(String value) {
            addCriterion("my_app_key <=", value, "myAppKey");
            return (Criteria) this;
        }

        public Criteria andMyAppKeyLike(String value) {
            addCriterion("my_app_key like", value, "myAppKey");
            return (Criteria) this;
        }

        public Criteria andMyAppKeyNotLike(String value) {
            addCriterion("my_app_key not like", value, "myAppKey");
            return (Criteria) this;
        }

        public Criteria andMyAppKeyIn(List<String> values) {
            addCriterion("my_app_key in", values, "myAppKey");
            return (Criteria) this;
        }

        public Criteria andMyAppKeyNotIn(List<String> values) {
            addCriterion("my_app_key not in", values, "myAppKey");
            return (Criteria) this;
        }

        public Criteria andMyAppKeyBetween(String value1, String value2) {
            addCriterion("my_app_key between", value1, value2, "myAppKey");
            return (Criteria) this;
        }

        public Criteria andMyAppKeyNotBetween(String value1, String value2) {
            addCriterion("my_app_key not between", value1, value2, "myAppKey");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCountIsNull() {
            addCriterion("count is null");
            return (Criteria) this;
        }

        public Criteria andCountIsNotNull() {
            addCriterion("count is not null");
            return (Criteria) this;
        }

        public Criteria andCountEqualTo(Integer value) {
            addCriterion("count =", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotEqualTo(Integer value) {
            addCriterion("count <>", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThan(Integer value) {
            addCriterion("count >", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("count >=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThan(Integer value) {
            addCriterion("count <", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountLessThanOrEqualTo(Integer value) {
            addCriterion("count <=", value, "count");
            return (Criteria) this;
        }

        public Criteria andCountIn(List<Integer> values) {
            addCriterion("count in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotIn(List<Integer> values) {
            addCriterion("count not in", values, "count");
            return (Criteria) this;
        }

        public Criteria andCountBetween(Integer value1, Integer value2) {
            addCriterion("count between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andCountNotBetween(Integer value1, Integer value2) {
            addCriterion("count not between", value1, value2, "count");
            return (Criteria) this;
        }

        public Criteria andUpMateUrlIsNull() {
            addCriterion("up_mate_url is null");
            return (Criteria) this;
        }

        public Criteria andUpMateUrlIsNotNull() {
            addCriterion("up_mate_url is not null");
            return (Criteria) this;
        }

        public Criteria andUpMateUrlEqualTo(String value) {
            addCriterion("up_mate_url =", value, "upMateUrl");
            return (Criteria) this;
        }

        public Criteria andUpMateUrlNotEqualTo(String value) {
            addCriterion("up_mate_url <>", value, "upMateUrl");
            return (Criteria) this;
        }

        public Criteria andUpMateUrlGreaterThan(String value) {
            addCriterion("up_mate_url >", value, "upMateUrl");
            return (Criteria) this;
        }

        public Criteria andUpMateUrlGreaterThanOrEqualTo(String value) {
            addCriterion("up_mate_url >=", value, "upMateUrl");
            return (Criteria) this;
        }

        public Criteria andUpMateUrlLessThan(String value) {
            addCriterion("up_mate_url <", value, "upMateUrl");
            return (Criteria) this;
        }

        public Criteria andUpMateUrlLessThanOrEqualTo(String value) {
            addCriterion("up_mate_url <=", value, "upMateUrl");
            return (Criteria) this;
        }

        public Criteria andUpMateUrlLike(String value) {
            addCriterion("up_mate_url like", value, "upMateUrl");
            return (Criteria) this;
        }

        public Criteria andUpMateUrlNotLike(String value) {
            addCriterion("up_mate_url not like", value, "upMateUrl");
            return (Criteria) this;
        }

        public Criteria andUpMateUrlIn(List<String> values) {
            addCriterion("up_mate_url in", values, "upMateUrl");
            return (Criteria) this;
        }

        public Criteria andUpMateUrlNotIn(List<String> values) {
            addCriterion("up_mate_url not in", values, "upMateUrl");
            return (Criteria) this;
        }

        public Criteria andUpMateUrlBetween(String value1, String value2) {
            addCriterion("up_mate_url between", value1, value2, "upMateUrl");
            return (Criteria) this;
        }

        public Criteria andUpMateUrlNotBetween(String value1, String value2) {
            addCriterion("up_mate_url not between", value1, value2, "upMateUrl");
            return (Criteria) this;
        }

        public Criteria andFreeAuditIsNull() {
            addCriterion("free_audit is null");
            return (Criteria) this;
        }

        public Criteria andFreeAuditIsNotNull() {
            addCriterion("free_audit is not null");
            return (Criteria) this;
        }

        public Criteria andFreeAuditEqualTo(Integer value) {
            addCriterion("free_audit =", value, "freeAudit");
            return (Criteria) this;
        }

        public Criteria andFreeAuditNotEqualTo(Integer value) {
            addCriterion("free_audit <>", value, "freeAudit");
            return (Criteria) this;
        }

        public Criteria andFreeAuditGreaterThan(Integer value) {
            addCriterion("free_audit >", value, "freeAudit");
            return (Criteria) this;
        }

        public Criteria andFreeAuditGreaterThanOrEqualTo(Integer value) {
            addCriterion("free_audit >=", value, "freeAudit");
            return (Criteria) this;
        }

        public Criteria andFreeAuditLessThan(Integer value) {
            addCriterion("free_audit <", value, "freeAudit");
            return (Criteria) this;
        }

        public Criteria andFreeAuditLessThanOrEqualTo(Integer value) {
            addCriterion("free_audit <=", value, "freeAudit");
            return (Criteria) this;
        }

        public Criteria andFreeAuditIn(List<Integer> values) {
            addCriterion("free_audit in", values, "freeAudit");
            return (Criteria) this;
        }

        public Criteria andFreeAuditNotIn(List<Integer> values) {
            addCriterion("free_audit not in", values, "freeAudit");
            return (Criteria) this;
        }

        public Criteria andFreeAuditBetween(Integer value1, Integer value2) {
            addCriterion("free_audit between", value1, value2, "freeAudit");
            return (Criteria) this;
        }

        public Criteria andFreeAuditNotBetween(Integer value1, Integer value2) {
            addCriterion("free_audit not between", value1, value2, "freeAudit");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table union_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table union_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}