spring:
  datasource:
    master:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/ds0?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave1:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/ds0-r1?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      #\u5982\u679C\u9700\u8981\uFF0C\u53EF\u914D\u7F6E\u53EA\u8BFB\u8D26\u6237
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
    slave2:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/ds0-r2?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
      #\u5982\u679C\u9700\u8981\uFF0C\u53EF\u914D\u7F6E\u53EA\u8BFB\u8D26\u6237
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis\u914D\u7F6E
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
#\u7B54\u5E94mybatis\u65E5\u5FD7
logging:
  level:
    com:
      gzzsc:
        lai:
          mapper: debug