package com.gzzsc.lai.provider.entity;

import java.util.Date;

public class Advertisement {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.customer_id
     *
     * @mbggenerated
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.contract_id
     *
     * @mbggenerated
     */
    private String contractId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.begin_time
     *
     * @mbggenerated
     */
    private Date beginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.end_time
     *
     * @mbggenerated
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.account_id
     *
     * @mbggenerated
     */
    private String accountId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.role_level
     *
     * @mbggenerated
     */
    private String roleLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.attchment_id
     *
     * @mbggenerated
     */
    private String attchmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.time
     *
     * @mbggenerated
     */
    private Short time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.comment
     *
     * @mbggenerated
     */
    private String comment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.modified_time
     *
     * @mbggenerated
     */
    private Date modifiedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.enable
     *
     * @mbggenerated
     */
    private Byte enable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.ae_status
     *
     * @mbggenerated
     */
    private Byte aeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.classify
     *
     * @mbggenerated
     */
    private Integer classify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.user_saw_times
     *
     * @mbggenerated
     */
    private String userSawTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.play_times
     *
     * @mbggenerated
     */
    private String playTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.schedule_beginTime
     *
     * @mbggenerated
     */
    private Date scheduleBegintime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.schedule_endTime
     *
     * @mbggenerated
     */
    private Date scheduleEndtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.open_times
     *
     * @mbggenerated
     */
    private Long openTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column advertisement.jump_times
     *
     * @mbggenerated
     */
    private Long jumpTimes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.id
     *
     * @return the value of advertisement.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.id
     *
     * @param id the value for advertisement.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.name
     *
     * @return the value of advertisement.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.name
     *
     * @param name the value for advertisement.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.customer_id
     *
     * @return the value of advertisement.customer_id
     *
     * @mbggenerated
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.customer_id
     *
     * @param customerId the value for advertisement.customer_id
     *
     * @mbggenerated
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId == null ? null : customerId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.contract_id
     *
     * @return the value of advertisement.contract_id
     *
     * @mbggenerated
     */
    public String getContractId() {
        return contractId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.contract_id
     *
     * @param contractId the value for advertisement.contract_id
     *
     * @mbggenerated
     */
    public void setContractId(String contractId) {
        this.contractId = contractId == null ? null : contractId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.begin_time
     *
     * @return the value of advertisement.begin_time
     *
     * @mbggenerated
     */
    public Date getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.begin_time
     *
     * @param beginTime the value for advertisement.begin_time
     *
     * @mbggenerated
     */
    public void setBeginTime(Date beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.end_time
     *
     * @return the value of advertisement.end_time
     *
     * @mbggenerated
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.end_time
     *
     * @param endTime the value for advertisement.end_time
     *
     * @mbggenerated
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.account_id
     *
     * @return the value of advertisement.account_id
     *
     * @mbggenerated
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.account_id
     *
     * @param accountId the value for advertisement.account_id
     *
     * @mbggenerated
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.role_level
     *
     * @return the value of advertisement.role_level
     *
     * @mbggenerated
     */
    public String getRoleLevel() {
        return roleLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.role_level
     *
     * @param roleLevel the value for advertisement.role_level
     *
     * @mbggenerated
     */
    public void setRoleLevel(String roleLevel) {
        this.roleLevel = roleLevel == null ? null : roleLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.attchment_id
     *
     * @return the value of advertisement.attchment_id
     *
     * @mbggenerated
     */
    public String getAttchmentId() {
        return attchmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.attchment_id
     *
     * @param attchmentId the value for advertisement.attchment_id
     *
     * @mbggenerated
     */
    public void setAttchmentId(String attchmentId) {
        this.attchmentId = attchmentId == null ? null : attchmentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.time
     *
     * @return the value of advertisement.time
     *
     * @mbggenerated
     */
    public Short getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.time
     *
     * @param time the value for advertisement.time
     *
     * @mbggenerated
     */
    public void setTime(Short time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.remark
     *
     * @return the value of advertisement.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.remark
     *
     * @param remark the value for advertisement.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.comment
     *
     * @return the value of advertisement.comment
     *
     * @mbggenerated
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.comment
     *
     * @param comment the value for advertisement.comment
     *
     * @mbggenerated
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.status
     *
     * @return the value of advertisement.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.status
     *
     * @param status the value for advertisement.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.create_time
     *
     * @return the value of advertisement.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.create_time
     *
     * @param createTime the value for advertisement.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.modified_time
     *
     * @return the value of advertisement.modified_time
     *
     * @mbggenerated
     */
    public Date getModifiedTime() {
        return modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.modified_time
     *
     * @param modifiedTime the value for advertisement.modified_time
     *
     * @mbggenerated
     */
    public void setModifiedTime(Date modifiedTime) {
        this.modifiedTime = modifiedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.type
     *
     * @return the value of advertisement.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.type
     *
     * @param type the value for advertisement.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.enable
     *
     * @return the value of advertisement.enable
     *
     * @mbggenerated
     */
    public Byte getEnable() {
        return enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.enable
     *
     * @param enable the value for advertisement.enable
     *
     * @mbggenerated
     */
    public void setEnable(Byte enable) {
        this.enable = enable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.ae_status
     *
     * @return the value of advertisement.ae_status
     *
     * @mbggenerated
     */
    public Byte getAeStatus() {
        return aeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.ae_status
     *
     * @param aeStatus the value for advertisement.ae_status
     *
     * @mbggenerated
     */
    public void setAeStatus(Byte aeStatus) {
        this.aeStatus = aeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.classify
     *
     * @return the value of advertisement.classify
     *
     * @mbggenerated
     */
    public Integer getClassify() {
        return classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.classify
     *
     * @param classify the value for advertisement.classify
     *
     * @mbggenerated
     */
    public void setClassify(Integer classify) {
        this.classify = classify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.user_saw_times
     *
     * @return the value of advertisement.user_saw_times
     *
     * @mbggenerated
     */
    public String getUserSawTimes() {
        return userSawTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.user_saw_times
     *
     * @param userSawTimes the value for advertisement.user_saw_times
     *
     * @mbggenerated
     */
    public void setUserSawTimes(String userSawTimes) {
        this.userSawTimes = userSawTimes == null ? null : userSawTimes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.play_times
     *
     * @return the value of advertisement.play_times
     *
     * @mbggenerated
     */
    public String getPlayTimes() {
        return playTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.play_times
     *
     * @param playTimes the value for advertisement.play_times
     *
     * @mbggenerated
     */
    public void setPlayTimes(String playTimes) {
        this.playTimes = playTimes == null ? null : playTimes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.schedule_beginTime
     *
     * @return the value of advertisement.schedule_beginTime
     *
     * @mbggenerated
     */
    public Date getScheduleBegintime() {
        return scheduleBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.schedule_beginTime
     *
     * @param scheduleBegintime the value for advertisement.schedule_beginTime
     *
     * @mbggenerated
     */
    public void setScheduleBegintime(Date scheduleBegintime) {
        this.scheduleBegintime = scheduleBegintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.schedule_endTime
     *
     * @return the value of advertisement.schedule_endTime
     *
     * @mbggenerated
     */
    public Date getScheduleEndtime() {
        return scheduleEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.schedule_endTime
     *
     * @param scheduleEndtime the value for advertisement.schedule_endTime
     *
     * @mbggenerated
     */
    public void setScheduleEndtime(Date scheduleEndtime) {
        this.scheduleEndtime = scheduleEndtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.open_times
     *
     * @return the value of advertisement.open_times
     *
     * @mbggenerated
     */
    public Long getOpenTimes() {
        return openTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.open_times
     *
     * @param openTimes the value for advertisement.open_times
     *
     * @mbggenerated
     */
    public void setOpenTimes(Long openTimes) {
        this.openTimes = openTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column advertisement.jump_times
     *
     * @return the value of advertisement.jump_times
     *
     * @mbggenerated
     */
    public Long getJumpTimes() {
        return jumpTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column advertisement.jump_times
     *
     * @param jumpTimes the value for advertisement.jump_times
     *
     * @mbggenerated
     */
    public void setJumpTimes(Long jumpTimes) {
        this.jumpTimes = jumpTimes;
    }
}