package com.gzzsc.lai.provider.entity;

import java.util.Date;

public class Community {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.serial
     *
     * @mbggenerated
     */
    private String serial;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.organization_seq
     *
     * @mbggenerated
     */
    private String organizationSeq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.province
     *
     * @mbggenerated
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.city
     *
     * @mbggenerated
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.town
     *
     * @mbggenerated
     */
    private String town;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.type
     *
     * @mbggenerated
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.family_count
     *
     * @mbggenerated
     */
    private Integer familyCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.people_count
     *
     * @mbggenerated
     */
    private Integer peopleCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.terminal_count
     *
     * @mbggenerated
     */
    private Integer terminalCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.grand_card_count
     *
     * @mbggenerated
     */
    private Integer grandCardCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.enable_promotion_active
     *
     * @mbggenerated
     */
    private Boolean enablePromotionActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.active_location_detail
     *
     * @mbggenerated
     */
    private String activeLocationDetail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.community_type
     *
     * @mbggenerated
     */
    private Integer communityType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.translate_status
     *
     * @mbggenerated
     */
    private Byte translateStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.poi_address
     *
     * @mbggenerated
     */
    private String poiAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.baidu_address
     *
     * @mbggenerated
     */
    private String baiduAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.is_join_sdk
     *
     * @mbggenerated
     */
    private Boolean isJoinSdk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.is_u_import
     *
     * @mbggenerated
     */
    private Boolean isUImport;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.media_type
     *
     * @mbggenerated
     */
    private Short mediaType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.media_company_name
     *
     * @mbggenerated
     */
    private String mediaCompanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.media_app_id
     *
     * @mbggenerated
     */
    private String mediaAppId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.union_id
     *
     * @mbggenerated
     */
    private String unionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.union_name
     *
     * @mbggenerated
     */
    private String unionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.resolution_x
     *
     * @mbggenerated
     */
    private String resolutionX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.resolution_y
     *
     * @mbggenerated
     */
    private String resolutionY;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.id
     *
     * @return the value of community.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.id
     *
     * @param id the value for community.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.name
     *
     * @return the value of community.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.name
     *
     * @param name the value for community.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.address
     *
     * @return the value of community.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.address
     *
     * @param address the value for community.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.serial
     *
     * @return the value of community.serial
     *
     * @mbggenerated
     */
    public String getSerial() {
        return serial;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.serial
     *
     * @param serial the value for community.serial
     *
     * @mbggenerated
     */
    public void setSerial(String serial) {
        this.serial = serial == null ? null : serial.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.organization_seq
     *
     * @return the value of community.organization_seq
     *
     * @mbggenerated
     */
    public String getOrganizationSeq() {
        return organizationSeq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.organization_seq
     *
     * @param organizationSeq the value for community.organization_seq
     *
     * @mbggenerated
     */
    public void setOrganizationSeq(String organizationSeq) {
        this.organizationSeq = organizationSeq == null ? null : organizationSeq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.province
     *
     * @return the value of community.province
     *
     * @mbggenerated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.province
     *
     * @param province the value for community.province
     *
     * @mbggenerated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.city
     *
     * @return the value of community.city
     *
     * @mbggenerated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.city
     *
     * @param city the value for community.city
     *
     * @mbggenerated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.country
     *
     * @return the value of community.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.country
     *
     * @param country the value for community.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.town
     *
     * @return the value of community.town
     *
     * @mbggenerated
     */
    public String getTown() {
        return town;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.town
     *
     * @param town the value for community.town
     *
     * @mbggenerated
     */
    public void setTown(String town) {
        this.town = town == null ? null : town.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.create_time
     *
     * @return the value of community.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.create_time
     *
     * @param createTime the value for community.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.update_time
     *
     * @return the value of community.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.update_time
     *
     * @param updateTime the value for community.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.type
     *
     * @return the value of community.type
     *
     * @mbggenerated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.type
     *
     * @param type the value for community.type
     *
     * @mbggenerated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.family_count
     *
     * @return the value of community.family_count
     *
     * @mbggenerated
     */
    public Integer getFamilyCount() {
        return familyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.family_count
     *
     * @param familyCount the value for community.family_count
     *
     * @mbggenerated
     */
    public void setFamilyCount(Integer familyCount) {
        this.familyCount = familyCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.people_count
     *
     * @return the value of community.people_count
     *
     * @mbggenerated
     */
    public Integer getPeopleCount() {
        return peopleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.people_count
     *
     * @param peopleCount the value for community.people_count
     *
     * @mbggenerated
     */
    public void setPeopleCount(Integer peopleCount) {
        this.peopleCount = peopleCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.terminal_count
     *
     * @return the value of community.terminal_count
     *
     * @mbggenerated
     */
    public Integer getTerminalCount() {
        return terminalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.terminal_count
     *
     * @param terminalCount the value for community.terminal_count
     *
     * @mbggenerated
     */
    public void setTerminalCount(Integer terminalCount) {
        this.terminalCount = terminalCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.grand_card_count
     *
     * @return the value of community.grand_card_count
     *
     * @mbggenerated
     */
    public Integer getGrandCardCount() {
        return grandCardCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.grand_card_count
     *
     * @param grandCardCount the value for community.grand_card_count
     *
     * @mbggenerated
     */
    public void setGrandCardCount(Integer grandCardCount) {
        this.grandCardCount = grandCardCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.enable_promotion_active
     *
     * @return the value of community.enable_promotion_active
     *
     * @mbggenerated
     */
    public Boolean getEnablePromotionActive() {
        return enablePromotionActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.enable_promotion_active
     *
     * @param enablePromotionActive the value for community.enable_promotion_active
     *
     * @mbggenerated
     */
    public void setEnablePromotionActive(Boolean enablePromotionActive) {
        this.enablePromotionActive = enablePromotionActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.active_location_detail
     *
     * @return the value of community.active_location_detail
     *
     * @mbggenerated
     */
    public String getActiveLocationDetail() {
        return activeLocationDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.active_location_detail
     *
     * @param activeLocationDetail the value for community.active_location_detail
     *
     * @mbggenerated
     */
    public void setActiveLocationDetail(String activeLocationDetail) {
        this.activeLocationDetail = activeLocationDetail == null ? null : activeLocationDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.community_type
     *
     * @return the value of community.community_type
     *
     * @mbggenerated
     */
    public Integer getCommunityType() {
        return communityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.community_type
     *
     * @param communityType the value for community.community_type
     *
     * @mbggenerated
     */
    public void setCommunityType(Integer communityType) {
        this.communityType = communityType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.translate_status
     *
     * @return the value of community.translate_status
     *
     * @mbggenerated
     */
    public Byte getTranslateStatus() {
        return translateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.translate_status
     *
     * @param translateStatus the value for community.translate_status
     *
     * @mbggenerated
     */
    public void setTranslateStatus(Byte translateStatus) {
        this.translateStatus = translateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.poi_address
     *
     * @return the value of community.poi_address
     *
     * @mbggenerated
     */
    public String getPoiAddress() {
        return poiAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.poi_address
     *
     * @param poiAddress the value for community.poi_address
     *
     * @mbggenerated
     */
    public void setPoiAddress(String poiAddress) {
        this.poiAddress = poiAddress == null ? null : poiAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.baidu_address
     *
     * @return the value of community.baidu_address
     *
     * @mbggenerated
     */
    public String getBaiduAddress() {
        return baiduAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.baidu_address
     *
     * @param baiduAddress the value for community.baidu_address
     *
     * @mbggenerated
     */
    public void setBaiduAddress(String baiduAddress) {
        this.baiduAddress = baiduAddress == null ? null : baiduAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.is_join_sdk
     *
     * @return the value of community.is_join_sdk
     *
     * @mbggenerated
     */
    public Boolean getIsJoinSdk() {
        return isJoinSdk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.is_join_sdk
     *
     * @param isJoinSdk the value for community.is_join_sdk
     *
     * @mbggenerated
     */
    public void setIsJoinSdk(Boolean isJoinSdk) {
        this.isJoinSdk = isJoinSdk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.is_u_import
     *
     * @return the value of community.is_u_import
     *
     * @mbggenerated
     */
    public Boolean getIsUImport() {
        return isUImport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.is_u_import
     *
     * @param isUImport the value for community.is_u_import
     *
     * @mbggenerated
     */
    public void setIsUImport(Boolean isUImport) {
        this.isUImport = isUImport;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.media_type
     *
     * @return the value of community.media_type
     *
     * @mbggenerated
     */
    public Short getMediaType() {
        return mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.media_type
     *
     * @param mediaType the value for community.media_type
     *
     * @mbggenerated
     */
    public void setMediaType(Short mediaType) {
        this.mediaType = mediaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.media_company_name
     *
     * @return the value of community.media_company_name
     *
     * @mbggenerated
     */
    public String getMediaCompanyName() {
        return mediaCompanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.media_company_name
     *
     * @param mediaCompanyName the value for community.media_company_name
     *
     * @mbggenerated
     */
    public void setMediaCompanyName(String mediaCompanyName) {
        this.mediaCompanyName = mediaCompanyName == null ? null : mediaCompanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.media_app_id
     *
     * @return the value of community.media_app_id
     *
     * @mbggenerated
     */
    public String getMediaAppId() {
        return mediaAppId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.media_app_id
     *
     * @param mediaAppId the value for community.media_app_id
     *
     * @mbggenerated
     */
    public void setMediaAppId(String mediaAppId) {
        this.mediaAppId = mediaAppId == null ? null : mediaAppId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.union_id
     *
     * @return the value of community.union_id
     *
     * @mbggenerated
     */
    public String getUnionId() {
        return unionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.union_id
     *
     * @param unionId the value for community.union_id
     *
     * @mbggenerated
     */
    public void setUnionId(String unionId) {
        this.unionId = unionId == null ? null : unionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.union_name
     *
     * @return the value of community.union_name
     *
     * @mbggenerated
     */
    public String getUnionName() {
        return unionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.union_name
     *
     * @param unionName the value for community.union_name
     *
     * @mbggenerated
     */
    public void setUnionName(String unionName) {
        this.unionName = unionName == null ? null : unionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.resolution_x
     *
     * @return the value of community.resolution_x
     *
     * @mbggenerated
     */
    public String getResolutionX() {
        return resolutionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.resolution_x
     *
     * @param resolutionX the value for community.resolution_x
     *
     * @mbggenerated
     */
    public void setResolutionX(String resolutionX) {
        this.resolutionX = resolutionX == null ? null : resolutionX.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.resolution_y
     *
     * @return the value of community.resolution_y
     *
     * @mbggenerated
     */
    public String getResolutionY() {
        return resolutionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.resolution_y
     *
     * @param resolutionY the value for community.resolution_y
     *
     * @mbggenerated
     */
    public void setResolutionY(String resolutionY) {
        this.resolutionY = resolutionY == null ? null : resolutionY.trim();
    }
}