server:
  port: 80
  servlet:
    context-path: /hystrix
spring:
  application:
    name: demo-hystrix
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-cluster7001.com:7001/eureka/
  instance:
    prefer-ip-address: true
#feign的配置，连接超时及读取超时配置
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 1000
        loggerLevel: basic
  hystrix:
    enabled: true
#actuator允许访问端点hystrix.stream
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
      base-path: /

