package com.gzzsc.lai.entity;

public class CommunityWithBLOBs extends Community {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.mall_name
     *
     * @mbggenerated
     */
    private String mallName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.treatment_department_name
     *
     * @mbggenerated
     */
    private String treatmentDepartmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.education_department_name
     *
     * @mbggenerated
     */
    private String educationDepartmentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column community.banking_department_name
     *
     * @mbggenerated
     */
    private String bankingDepartmentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.mall_name
     *
     * @return the value of community.mall_name
     *
     * @mbggenerated
     */
    public String getMallName() {
        return mallName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.mall_name
     *
     * @param mallName the value for community.mall_name
     *
     * @mbggenerated
     */
    public void setMallName(String mallName) {
        this.mallName = mallName == null ? null : mallName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.treatment_department_name
     *
     * @return the value of community.treatment_department_name
     *
     * @mbggenerated
     */
    public String getTreatmentDepartmentName() {
        return treatmentDepartmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.treatment_department_name
     *
     * @param treatmentDepartmentName the value for community.treatment_department_name
     *
     * @mbggenerated
     */
    public void setTreatmentDepartmentName(String treatmentDepartmentName) {
        this.treatmentDepartmentName = treatmentDepartmentName == null ? null : treatmentDepartmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.education_department_name
     *
     * @return the value of community.education_department_name
     *
     * @mbggenerated
     */
    public String getEducationDepartmentName() {
        return educationDepartmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.education_department_name
     *
     * @param educationDepartmentName the value for community.education_department_name
     *
     * @mbggenerated
     */
    public void setEducationDepartmentName(String educationDepartmentName) {
        this.educationDepartmentName = educationDepartmentName == null ? null : educationDepartmentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column community.banking_department_name
     *
     * @return the value of community.banking_department_name
     *
     * @mbggenerated
     */
    public String getBankingDepartmentName() {
        return bankingDepartmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column community.banking_department_name
     *
     * @param bankingDepartmentName the value for community.banking_department_name
     *
     * @mbggenerated
     */
    public void setBankingDepartmentName(String bankingDepartmentName) {
        this.bankingDepartmentName = bankingDepartmentName == null ? null : bankingDepartmentName.trim();
    }
}